import type { Concept } from './types';

export const concepts: Concept[] = [
    { id: 'NL01', title: 'Nguyên lý về mối liên hệ phổ biến', explanation: 'Sự vật không tồn tại biệt lập. Các mặt của nó tác động, quy định và có thể làm thay đổi lẫn nhau; những mối liên hệ ấy khách quan, phổ biến và rất đa dạng.', application: 'Trong hồ sơ, yêu cầu dữ liệu, giao diện, API, test và quyết định trình bày thuộc cùng một hệ thống. Cần tìm quan hệ chủ yếu thay vì chỉ liệt kê mọi yếu tố có mặt.', limit: 'Xem xét toàn diện không có nghĩa mọi yếu tố quan trọng như nhau hay tác động trực tiếp. Luôn xác định phạm vi, thời điểm và điều kiện cụ thể.', pages: [5, 8], slide: 'Tiết 16 · slide 7–19' },
    { id: 'NL02', title: 'Nguyên lý về sự phát triển', explanation: 'Phát triển là quá trình vận động theo hướng từ thấp đến cao, từ kém hoàn thiện đến hoàn thiện hơn. Nó có tính khách quan, phổ biến, kế thừa và diễn ra dưới nhiều hình thức.', application: 'V3 được xem là tiến bộ trong phạm vi mô phỏng vì nó khắc phục luồng dữ liệu và qua test đã nêu. V1 đổi cách trình bày, V2 thêm chức năng phụ, nhưng chưa giải quyết nhiệm vụ cốt lõi.', limit: 'Không phải mọi thay đổi, tăng về số lượng hay phiên bản mới đều là phát triển. Cần xét nó đã làm năng lực thực hiện nhiệm vụ thay đổi thế nào.', pages: [8, 11], slide: 'Tiết 16 · slide 20–27' },
    { id: 'QL01', title: 'Quy luật chuyển hóa từ lượng thành chất và ngược lại', explanation: 'Lượng có thể thay đổi trong một giới hạn mà chất cơ bản chưa đổi. Khi đạt giới hạn trong điều kiện phù hợp, sự thay đổi lượng có thể dẫn đến bước chuyển hóa về chất; chất mới lại quy định lượng mới.', application: 'Trong mô hình A→D, số liên kết là mặt lượng đang xét. Liên kết B→C đúng vị trí tạo điều kiện để toàn bộ luồng vận hành, tức xuất hiện chất mới trong mô hình.', limit: 'Mô hình chỉ là minh họa. Không có một con số “điểm nút” chung cho mọi hệ thống; điểm nút cũng khác với quá trình bước nhảy.', pages: [28, 32], slide: 'Tiết 20 · slide 9–18' },
    { id: 'QL02', title: 'Quy luật thống nhất và đấu tranh của các mặt đối lập', explanation: 'Trong một chỉnh thể, các mặt đối lập vừa cần nhau để tồn tại vừa có xu hướng hạn chế, phủ định lẫn nhau. Sự thống nhất và đấu tranh đó là nguồn gốc, động lực bên trong của vận động và phát triển.', application: 'Chuẩn chung giúp các phần tích hợp; quyền chủ động giúp công việc không bị nghẽn. Khi một phía bị tuyệt đối hóa, quy trình xuất hiện mâu thuẫn cần được giải quyết bằng tổ chức phù hợp.', limit: 'Không phải mọi khác biệt hay cuộc tranh luận đều là mâu thuẫn biện chứng. Trước hết phải xác định hai mặt có thuộc cùng một quan hệ và tác động lẫn nhau hay không.', pages: [32, 35], slide: 'Tiết 21 · slide 5–12' },
    { id: 'QL03', title: 'Quy luật phủ định của phủ định', explanation: 'Phát triển diễn ra qua những lần phủ định biện chứng: cái mới thay thế cái cũ trên cơ sở giữ lại và cải biến những yếu tố còn phù hợp. Một số nét ban đầu có thể trở lại ở trình độ cao hơn.', application: 'A′ giữ sự chủ động theo phạm vi từ A, kế thừa chuẩn chung từ B, đồng thời bổ sung test và trách nhiệm bàn giao. Đây là phương án cải biến, không quay về nguyên trạng nào.', limit: 'A′ chỉ là mô phỏng sư phạm. Không phải hai lần thay đổi bất kỳ đều tạo thành một chu kỳ phủ định của phủ định; quá trình thực tế có thể có nhiều khâu trung gian.', pages: [35, 37], slide: 'Tiết 21 · slide 13–22' },
    { id: 'PT01', title: 'Cái riêng và cái chung', explanation: 'Cái riêng là một sự vật hay quá trình cụ thể. Cái chung là những thuộc tính, mối liên hệ lặp lại ở nhiều cái riêng; cái chung chỉ tồn tại thông qua các cái riêng.', application: 'C-A, C-B và C-C là ba hồ sơ cụ thể. C-A và C-B cùng thiếu sự thống nhất và test khi ghép hệ thống, nhưng lỗi cụ thể của mỗi hồ sơ vẫn khác nhau.', limit: 'Tìm thấy điểm chung ở hai hồ sơ không cho phép kết luận cho mọi dự án. Cái đơn nhất là một nét chỉ có ở một trường hợp trong phạm vi đang xét, không phải đồng nghĩa với một cá nhân.', pages: [13, 17], slide: 'Tiết 17 · slide 7–11' },
    { id: 'PT02', title: 'Nguyên nhân và kết quả', explanation: 'Nguyên nhân là sự tác động làm xuất hiện biến đổi; kết quả là biến đổi do tác động ấy tạo ra. Phải chứng minh quan hệ sản sinh, không chỉ dựa vào việc một sự kiện xảy ra trước.', application: 'Yêu cầu đổi dữ liệu, sự không tương thích giữa giao diện và API, rồi việc API từ chối dữ liệu tạo thành cơ chế của lỗi đăng ký. Nhật ký E04 và E05 cho phép kiểm tra cơ chế này.', limit: 'Cần phân biệt nguyên nhân với điều kiện và sự trùng hợp. Kết quả có thể tác động trở lại quá trình tiếp theo, nhưng không thể quay về tạo ra nguyên nhân đã có trong quá khứ.', pages: [17, 19], slide: 'Tiết 17 · slide 12–15' },
    { id: 'PT03', title: 'Tất nhiên và ngẫu nhiên', explanation: 'Tất nhiên là mối liên hệ do nguyên nhân cơ bản bên trong quy định và phải xảy ra trong điều kiện xác định. Ngẫu nhiên gắn với những hoàn cảnh bên ngoài trong quan hệ đang xét; cả hai đều có nguyên nhân.', application: 'Với đầu vào thiếu fullName và quy tắc kiểm tra giữ nguyên, API sẽ từ chối dữ liệu. Sự cố mạng có nguyên nhân riêng, ảnh hưởng việc chia sẻ nhưng không tạo lỗi cục bộ đã có trước đó.', limit: 'Gọi một sự cố là ngẫu nhiên không có nghĩa nó vô nguyên nhân hoặc không đáng quan tâm. Khi điều kiện đổi, phải đánh giá lại vai trò của các yếu tố.', pages: [19, 20], slide: 'Tiết 18 · slide 7–10' },
    { id: 'PT04', title: 'Nội dung và hình thức', explanation: 'Nội dung là tổng hợp các mặt, yếu tố và quá trình của sự vật. Hình thức là phương thức tồn tại, tổ chức và liên kết các yếu tố ấy.', application: 'Sáu mảnh dữ kiện của báo cáo vẫn là cùng một nội dung; khi được sắp theo yêu cầu, cơ chế, hậu quả, biện pháp và test, người đọc hiểu rõ hơn lập luận.', limit: 'Hình thức không chỉ là màu sắc hay trang trí. Không có một bố cục duy nhất cho mọi văn bản; cách tổ chức cần phù hợp nội dung và mục tiêu giao tiếp.', pages: [20, 22], slide: 'Tiết 18 · slide 11–13' },
    { id: 'PT05', title: 'Bản chất và hiện tượng', explanation: 'Bản chất là những mối liên hệ tất nhiên, tương đối ổn định bên trong sự vật. Hiện tượng là cách những mối liên hệ ấy biểu hiện ra trong điều kiện cụ thể; nhận thức cần đi từ hiện tượng đến bản chất.', application: 'Ảnh chụp tin nhắn là một biểu hiện cần đối chiếu với hội thoại đầy đủ, nhật ký trạng thái và kết quả test. Từ một câu nói không thể suy thẳng ra hành vi hay động cơ của Nam.', limit: 'Hiện tượng không phải lúc nào cũng sai hoặc vô giá trị; nó là điểm khởi đầu để kiểm tra. Bản chất cũng không phải điều có thể gán cho ai đó bằng cảm tính.', pages: [22, 24], slide: 'Tiết 19 · slide 7–9' },
    { id: 'PT06', title: 'Khả năng và hiện thực', explanation: 'Hiện thực là những gì đang tồn tại. Khả năng là điều chưa thành hiện thực nhưng có tiền đề trong hiện thực và có thể được thực hiện khi hội đủ điều kiện thích hợp.', application: 'Mã nguồn, bản sao lưu, dữ liệu mẫu và thời gian là tiền đề hiện có. Chuỗi chốt yêu cầu, chuyển đổi dữ liệu, test và chuẩn bị bản chạy tạo điều kiện để bản demo giới hạn trở thành hiện thực.', limit: 'Mong muốn không thay thế điều kiện. Bản demo chạy trong phạm vi đã test chưa đồng nghĩa với sản phẩm đã sẵn sàng sử dụng trong mọi môi trường.', pages: [24, 27], slide: 'Tiết 19 · slide 10–13' }
];
