import type { Evidence } from './types';

/** Hồ sơ HS-01 là tình huống hư cấu để người chơi thực hành phân tích biện chứng. */
export const evidence: Evidence[] = [
  { id: 'E01', chapter: 1, title: 'Ảnh chụp một đoạn tin nhắn', author: 'Nhóm Mạch Nối', time: 'Ngày D · 19:42', order: 1942, app: 'chat', summary: 'Một ảnh chụp chỉ giữ lại câu mở đầu của Nam. Nó cho thấy cậu ấy bức xúc, nhưng không cho biết Nam đã làm gì với mã nguồn.', body: ['“Nếu yêu cầu cứ thay đổi mà không báo bên thiết kế thì mình không thể tiếp tục làm như cũ…”'], fiction: true },
  { id: 'E02', chapter: 1, title: 'Thông báo vắng tên trong danh sách trình bày', author: 'Ban tổ chức triển lãm học phần', time: 'Ngày D · 19:50', order: 1950, app: 'mail', summary: 'Dự án “Mạch Nối” không còn xuất hiện trong danh sách công khai lúc 19:50. Thông báo chỉ xác nhận việc ẩn khỏi danh sách, chưa nói mã nguồn bị xóa.', body: ['Chào nhóm Mạch Nối,', 'Hệ thống ghi nhận dự án của nhóm không còn hiển thị trong danh sách trình bày từ 19:50. Buổi nghiệm thu bắt đầu lúc 20:00.', 'Vui lòng kiểm tra trạng thái dự án và phản hồi cho ban tổ chức nếu cần hỗ trợ.', 'Ban tổ chức học phần'], fiction: true },
  { id: 'E03', chapter: 1, title: 'Yêu cầu cập nhật dữ liệu · phiên bản 2', author: 'Quân · phụ trách yêu cầu', time: 'Ngày D · 18:10', order: 1810, app: 'mail', summary: 'Yêu cầu đầu vào đổi từ name sang fullName. API bắt buộc trường mới, nhưng email chưa xác nhận phần giao diện đã được cập nhật và test cùng API.', body: ['Gửi nhóm Mạch Nối,', 'Yêu cầu dữ liệu đã được cập nhật: trường name được thay bằng fullName. Kể từ phiên bản này, hệ thống sẽ yêu cầu bắt buộc trường fullName. Các phần liên quan cần được cập nhật đồng bộ và test lại luồng đăng ký trước giờ trình bày', 'Quân · Phụ trách yêu cầu và test'], table: [['Phiên bản', 'Trường bắt buộc'], ['v1', 'name'], ['v2 · 18:10', 'fullName']], fiction: true },
  { id: 'E04', chapter: 1, title: 'Biên bản đối chiếu giao diện và API', author: 'Quân · phụ trách test', time: 'Ngày D · 18:25', order: 1825, app: 'files', summary: 'Giao diện vẫn gửi name trong khi API yêu cầu fullName; chưa có bước chuyển đổi dữ liệu. Đây là quan hệ bên trong trực tiếp làm luồng đăng ký không khớp.', body: ['Kết quả kiểm tra lúc 18:25 cho thấy giao diện và API đang sử dụng hai quy ước dữ liệu khác nhau. Cần cập nhật một trong hai phía hoặc bổ sung bước chuyển đổi trước khi nghiệm thu.'], table: [['Thành phần', 'Dữ liệu đang dùng', 'Trạng thái'], ['Màn hình đăng ký', 'name', 'Chưa cập nhật'], ['API tiếp nhận', 'fullName', 'Từ chối dữ liệu thiếu trường'], ['Bước chuyển đổi', 'Chưa có', 'Cần bổ sung']], fiction: true },
  { id: 'E05', chapter: 1, title: 'Nhật ký test cục bộ · registration.log', author: 'Nam · lập trình giao diện', time: 'Ngày D · 19:20', order: 1920, app: 'terminal', summary: 'Khi chạy trên máy cục bộ, luồng đăng ký đã dừng vì thiếu fullName lúc 19:20 trước cả thời điểm mất mạng. Dữ kiện này giúp phân biệt lỗi dữ liệu với sự cố kết nối.', body: ['[19:20:00] RUN     registration / local', '[19:20:01] INPUT   { name: "Người dùng thử" }', '[19:20:01] REQUIRE fullName', '[19:20:01] ERROR   Missing required field: fullName', '[19:20:01] ABORT   Registration not saved', '[19:20:01] SKIP    Confirmation ticket not generated'], fiction: true },
  { id: 'E06', chapter: 1, title: 'Sự cố kết nối mạng', author: 'Nhật ký hạ tầng', time: 'Ngày D · 19:35–19:45', order: 1935, app: 'terminal', summary: 'Mạng gián đoạn mười phút, ảnh hưởng đến việc chia sẻ và cập nhật trực tuyến. Sự cố có nguyên nhân riêng, nhưng không tạo ra lỗi dữ liệu đã xuất hiện lúc 19:20.', body: ['[19:35:00] WARN    Kết nối mạng khu vực gián đoạn', '[19:35:02] IMPACT  Không thể đồng bộ hoặc chia sẻ online', '[19:45:00] OK      Kết nối được khôi phục'], fiction: true },
  { id: 'E07', chapter: 1, title: 'Toàn bộ cuộc trao đổi của nhóm', author: 'Nhóm Mạch Nối', time: 'Ngày D · 19:42–19:49', order: 1943, app: 'chat', summary: 'Đọc đủ ngữ cảnh cho thấy Nam không xóa mã nguồn; Linh đề nghị rút bản demo để tránh trình bày khi chưa test; Mai xác nhận chỉ ẩn dự án khỏi danh sách.', body: ['Nam|19:42|Nếu yêu cầu đổi mà không báo cho phần giao diện, mình không thể tiếp tục như cũ. Mã nguồn vẫn còn trên máy. Lỗi thiếu fullName đã xuất hiện khi test lúc 19:20; cần chốt dữ liệu rồi test lại.', 'Linh|19:47|Nếu hệ thống vẫn chưa được test đầy đủ, mình đề nghị tạm rút bản demo. Tối nay sửa xong thì sáng mai xin nghiệm thu lại.', 'Mai|19:49|Mình sẽ ẩn dự án khỏi danh sách trình bày, không xóa kho mã nguồn. Sáng mai cả nhóm họp để xử lý.'], fiction: true },
  { id: 'E08', chapter: 1, title: 'Nhật ký thay đổi trạng thái dự án', author: 'Mai · trưởng nhóm', time: 'Ngày D · 19:50', order: 1951, app: 'terminal', summary: 'Nhật ký ghi Mai đổi trạng thái hiển thị sang HIDDEN. Không có thao tác xóa kho mã nguồn; bản sao lưu và mã nguồn vẫn còn.', body: ['[19:50:00] ACTOR   Mai / Team lead', '[19:50:00] ACTION  Set demo visibility: HIDDEN', '[19:50:01] OK      Listing updated', '[19:50:01] AUDIT   No project deletion recorded', '[19:50:02] CHECK   Source code and backup available'], fiction: true },
  { id: 'E09', chapter: 1, title: 'Bảng chuẩn bị trước giờ trình bày', author: 'Quân · phụ trách test', time: 'Ngày D · 19:00', order: 1900, app: 'files', summary: 'Mỗi phần việc được báo là hoàn thành riêng lẻ, nhưng chưa có người nhận trách nhiệm test đầu-cuối. “Xong từng phần” chưa đồng nghĩa với “luồng chung hoạt động”.', body: ['Các phần việc đều đã có người phụ trách, nhưng chưa có biên bản kiểm thử khi kết hợp giao diện, API và dữ liệu thành một luồng hoàn chỉnh. Đây là điểm còn thiếu trước giờ trình bày.'], table: [['Hạng mục', 'Tình trạng'], ['Giao diện', 'Hoàn thành phần được giao'], ['API', 'Hoàn thành phần được giao'], ['Cơ sở dữ liệu', 'Sẵn sàng'], ['Test đầu-cuối', 'Chưa phân công']], fiction: true },
  { id: 'E10', chapter: 2, title: 'Ba hồ sơ đối chiếu', author: 'Quân · phụ trách test', time: 'Ngày D+1 · Hồ sơ so sánh', order: 3000, app: 'files', summary: 'C-A và C-B đều có sự không tương thích giữa các phần và thiếu test toàn luồng, nhưng lỗi cụ thể khác nhau. C-C đã test cục bộ nên vẫn chạy được dù không thể gửi thông báo khi mất mạng.', body: ['Ba hồ sơ là những trường hợp cụ thể. Việc chúng có một số đặc điểm giống nhau giúp nhận diện vấn đề chung, nhưng không cho phép kết luận mọi dự án đều thất bại theo cùng một cách.'], table: [['Hồ sơ', 'Hoàn cảnh', 'Kết quả'], ['C-A · Mạch Nối', 'Lệch name/fullName; chưa test tích hợp', 'Luồng đăng ký bị từ chối'], ['C-B · Nhóm B', 'Đổi tên API; chưa test tích hợp', 'Gọi sai đường dẫn API'], ['C-C · Nhóm C', 'Quy ước thống nhất; có bản chạy cục bộ', 'Luồng cục bộ hoạt động, chỉ gián đoạn gửi thông báo']], fiction: true },
  { id: 'E11', chapter: 2, title: 'Nhật ký quy trình · phương án A và B', author: 'Mai · trưởng nhóm', time: 'Ngày D−21 → D−3', order: 100, app: 'files', summary: 'Phương án A cho mỗi thành viên tự làm hoàn toàn, nhanh nhưng thiếu chuẩn chung. Phương án B tăng kiểm soát bằng một người duyệt mọi thay đổi, giảm lỗi nhưng tạo điểm nghẽn.', body: ['A · Ba tuần trước: Mỗi thành viên tự chọn cách đặt tên và tích hợp. Công việc nhanh lúc đầu nhưng khó ghép lại.', 'B · Hai tuần trước: Áp dụng quy ước chung; mọi thay đổi đều chờ một trưởng kỹ thuật phê duyệt.', 'Ba ngày trước: Danh sách chờ phê duyệt tăng lên, tiến độ bị dồn lại trước hạn.'], fiction: true },
  { id: 'E12', chapter: 2, title: 'Bản nháp báo cáo sự cố', author: 'Nhóm Mạch Nối', time: 'Ngày D+1 · 08:30', order: 3030, app: 'files', summary: 'Báo cáo có đủ sáu mảnh thông tin: yêu cầu, sự không tương thích, kết quả test, hậu quả, biện pháp và tiêu chí nghiệm thu. Người chơi cần tổ chức chúng thành một lập luận rõ ràng.', body: ['Biện pháp: bổ sung bước chuyển đổi dữ liệu.', 'Yêu cầu: trường name đổi thành fullName.', 'Nghiệm thu: test đầu-cuối với dữ liệu mẫu.', 'Kết quả test: thiếu trường bắt buộc.', 'Hậu quả: API từ chối lưu, bản demo bị tạm ẩn.', 'Nguyên nhân trực tiếp: giao diện gửi name, API yêu cầu fullName.'], fiction: true },
  { id: 'E13', chapter: 2, title: 'Biên bản họp về quy trình phê duyệt', author: 'Mai · trưởng nhóm', time: 'Ngày D−3', order: 200, app: 'mail', summary: 'Nhóm cần chuẩn chung để tích hợp, đồng thời cần quyền chủ động theo từng phần việc. Mâu thuẫn không nằm ở xung đột cá nhân mà ở hai yêu cầu vừa cần nhau vừa có thể kìm hãm nhau.', body: ['Gửi cả nhóm,', 'Khi mọi thay đổi đều chờ một người phê duyệt, tiến độ bị nghẽn. Nhưng nếu không có quy ước chung, các phần lại khó ghép với nhau.', 'Đề nghị giữ coding convention, phân rõ phạm vi phụ trách và cho phép chủ động phê duyệt trong từng mô-đun; các thay đổi liên mô-đun vẫn cần test chung.', 'Mai · Trưởng nhóm'], fiction: true },
  { id: 'E14', chapter: 3, title: 'Mô hình luồng A → D', author: 'Phòng mô phỏng', time: 'Mô phỏng · Không phải sự kiện đã xảy ra', order: 4000, app: 'lab', summary: 'Bốn nút biểu diễn một luồng xử lý. Thêm một liên kết đúng vị trí B→C giúp hệ thống đi từ nhận dữ liệu đến tạo phiếu; số liên kết chỉ có ý nghĩa trong cấu trúc phù hợp.', body: ['A: Nhận dữ liệu. B: Kiểm tra. C: Lưu trữ. D: Tạo phiếu xác nhận.', 'B→A là phản hồi để nhập lại. Muốn luồng hoàn chỉnh phải có liên kết B→C; thêm liên kết tùy ý không bảo đảm hệ thống hoạt động.'], fiction: true },
  { id: 'E15', chapter: 3, title: 'Đề xuất quy trình A′', author: 'Phòng mô phỏng', time: 'Phương án dự kiến', order: 4010, app: 'lab', summary: 'A′ không quay về phương án tự do hoàn toàn, cũng không duy trì việc tập trung mọi phê duyệt vào một người. Nó kế thừa chủ động của A, chuẩn chung của B và bổ sung test tích hợp.', body: ['Phương án 1: Bỏ toàn bộ quy ước, để mỗi người tự quyết mọi thứ.', 'Phương án 2: Giữ mọi thay đổi phải qua một trưởng kỹ thuật.', 'Phương án 3: Chia phạm vi phụ trách, giữ quy ước chung, test tự động và test liên mô-đun.', 'Lưu ý: Đổi mới không phải xóa hết cái cũ; cần giữ lại những yếu tố còn phù hợp.'], fiction: true },
  { id: 'E16', chapter: 3, title: 'Đối chiếu ba bản xây dựng', author: 'Phòng mô phỏng', time: 'Ba bản thử giả định', order: 4020, app: 'lab', summary: 'V1 chỉ thay giao diện; V2 thêm tính năng phụ; V3 sửa luồng dữ liệu và qua test đã nêu. Thay đổi có ý nghĩa cần được đánh giá ở khả năng giải quyết nhiệm vụ cốt lõi.', body: ['Hãy so sánh các bản xây dựng bằng luồng đăng ký và kết quả test, không chỉ bằng số tính năng hay diện mạo.'], table: [['Bản xây dựng', 'Cập nhật', 'Test luồng cốt lõi'], ['V1', 'Đổi màu nút, thêm hiệu ứng', 'Vẫn lỗi dữ liệu'], ['V2', 'Thêm giao diện tối và nút chia sẻ', 'Luồng chính vẫn bị từ chối'], ['V3', 'Bổ sung chuyển đổi dữ liệu, test lại', 'Hoạt động trong môi trường cục bộ']], fiction: true },
  { id: 'E17', chapter: 3, title: 'Kế hoạch khôi phục bản demo · 60 phút', author: 'Mai · trưởng nhóm', time: 'Ngày D+1 · 09:00 → 10:00', order: 4030, app: 'mail', summary: 'Nhóm có mã nguồn, bản sao lưu, dữ liệu mẫu và người thực hiện. Đó là tiền đề thực tế; để biến khả năng khôi phục thành kết quả, các bước cốt lõi phải được làm theo đúng thứ tự trong 60 phút.', body: ['Còn 60 phút trước lượt nghiệm thu lại. Mã nguồn, bản sao lưu và dữ liệu mẫu đều sẵn sàng.', 'Mục tiêu là khôi phục một bản demo giới hạn nhưng đã được test, không phải cam kết sản phẩm hoàn chỉnh.'], table: [['Việc', 'Phút', 'Cần trước'], ['A1 · Chốt yêu cầu dữ liệu', '10', '—'], ['A2 · Viết bước chuyển name → fullName', '20', 'A1'], ['A3 · Test đầu-cuối', '15', 'A2'], ['A4 · Chuẩn bị bản chạy cục bộ và tài liệu', '10', 'A3 đạt'], ['A5 · Chỉnh hiệu ứng giao diện', '15', '—'], ['A6 · Thêm tính năng giới thiệu', '30', '—'], ['A7 · Chờ mạng ổn định rồi mới xử lý', '10', '—']], fiction: true }
];

export const chapters = [
  { id: 1, title: 'Dấu vết của sự cố', short: 'Điều tra', subtitle: 'Từ một dấu hiệu bề ngoài đến chuỗi dữ kiện có thể kiểm chứng.' },
  { id: 2, title: 'Bên trong hệ thống', short: 'Phân tích', subtitle: 'Một sự cố cụ thể có thể bộc lộ những mối liên hệ trong cả quy trình.' },
  { id: 3, title: 'Từ sự cố đến phương án mới', short: 'Tái thiết', subtitle: 'Biến bài học thành hành động có điều kiện và có kiểm chứng.' }
] as const;
