import type { Task, Option, Question } from './types';

const opts=(items:string[][]):Option[]=>items.map(([id,label])=>({id,label}));
const q=(id:string,label:string,correct:string,items:string[][]):Question=>({id,label,correct,options:opts(items)});

export const chainOptions=opts([
  ['network','Sự cố mạng xảy ra lúc 19:35'],['requirement','Yêu cầu đổi từ name sang fullName'],['failure','Luồng đăng ký không lưu được dữ liệu'],['message','Nam gửi tin nhắn lúc 19:42'],['mismatch','Giao diện chưa cập nhật, API yêu cầu quy ước mới'],['reject','API từ chối dữ liệu thiếu trường bắt buộc']
]);
export const reportOptions=opts([
  ['measure','Biện pháp: bổ sung bước chuyển đổi dữ liệu'],['req','Yêu cầu: đổi name thành fullName'],['retest','Nghiệm thu: kiểm thử lại với dữ liệu mẫu'],['test','Kết quả kiểm thử: thiếu trường bắt buộc'],['impact','Hậu quả: tạm ẩn bản demo'],['incompat','Không tương thích: giao diện gửi name, API yêu cầu fullName']
]);
export const relationOptions=opts([
  ['req_update','Yêu cầu thay đổi ↔ Các phần liên quan phải cập nhật đồng bộ'],['test_result','Kết quả kiểm thử ↔ Quyết định có trình bày bản demo hay không'],['color','Màu nhận diện của nhóm ↔ Tâm trạng khi thuyết trình'],['handover_test','Hoàn thành từng phần ↔ Kiểm thử khi ghép toàn bộ hệ thống'],['speaker','Người thuyết trình ↔ Người chuẩn bị nội dung'],['condition_fallback','Trình diễn trực tuyến ↔ Phương án dự phòng chạy cục bộ']
]);

export const recoveryActions=[
  {id:'A1',label:'Chốt yêu cầu dữ liệu',minutes:10,requires:null},
  {id:'A2',label:'Viết bước chuyển name → fullName',minutes:20,requires:'A1'},
  {id:'A3',label:'Kiểm thử đầu-cuối toàn hệ thống',minutes:15,requires:'A2'},
  {id:'A4',label:'Chuẩn bị bản chạy cục bộ và tài liệu',minutes:10,requires:'A3'},
  {id:'A5',label:'Chỉnh hiệu ứng giao diện',minutes:15,requires:null},
  {id:'A6',label:'Thêm tính năng giới thiệu mới',minutes:30,requires:null},
  {id:'A7',label:'Chờ mạng ổn định rồi mới xử lý',minutes:10,requires:null}
];

export const initialOptions=opts([
  ['sabotage','Nam bức xúc và đã xóa mã nguồn của dự án.'],['withdraw','Nhóm chủ động ẩn bản demo khỏi danh sách trình bày.'],['technical','Sự cố kỹ thuật khiến dự án không thể mở.'],['unknown','Chưa có đủ dữ kiện để kết luận.']
]);
export const verdictOptions=opts([
  ['V1','Nam đã phá hoại dự án vì bức xúc.'],['V2','Sự cố mạng là nguyên nhân duy nhất khiến dự án thất bại.'],['V3','Nhóm chủ động ẩn bản demo khi chưa kiểm thử; lỗi dữ liệu và quy trình là có thật, nhưng không có bằng chứng Nam phá hoại.'],['V4','Chưa thể kết luận nếu không đối chiếu thêm chứng cứ.']
]);

export const tasks:Task[]=[
  {id:'T01',chapter:1,concept:'PT05',kind:'classify',title:'Từ dấu hiệu đến sự thật',prompt:'Phân loại các nhận định: điều gì đã được xác nhận, điều gì mới là suy đoán? Dùng hai chứng cứ để bảo vệ kết luận của bạn.',evidence:['E01','E02','E07','E08'],hints:['So sánh ảnh chụp E01 với toàn bộ cuộc trao đổi E07.','E08 ghi nhận chính xác thao tác nào? Có thao tác xóa kho mã nguồn không?'],criteria:['Xác nhận dự án bị ẩn, chưa bị xóa','Không kết luận mã nguồn đã bị xóa','Không suy đoán động cơ của Nam','Kết luận dựa trên chứng cứ đối chiếu'],feedback:['E02 chỉ xác nhận dự án không hiển thị trên danh sách lúc 19:50.','E08 xác nhận mã nguồn và bản sao lưu vẫn còn.','E07 cho thấy Nam bức xúc nhưng không có hành vi xóa dự án.','Kết luận phù hợp cần dựa trên E07 và E08: nhóm đã ẩn bản demo, không có bằng chứng Nam phá hoại.']},
  {id:'T02',chapter:1,concept:'PT02',kind:'chain',title:'Lần theo chuỗi nguyên nhân',prompt:'Sắp bốn sự kiện thành cơ chế dẫn đến lỗi đăng ký. Hãy ưu tiên quan hệ tạo ra kết quả, không chỉ xếp theo thời điểm.',evidence:['E03','E04','E05','E06','E08'],hints:['E05 diễn ra trước khi mạng gián đoạn.','Đối chiếu yêu cầu mới trong E03 với dữ liệu được gửi ở E04 và E05.'],criteria:['Chọn đúng bốn mắt xích gây lỗi','Sắp đúng trình tự của luồng xử lý','Dùng chứng cứ để kiểm tra cơ chế','Phân biệt lỗi kỹ thuật với quyết định ẩn demo'],feedback:['Chuỗi cần tìm bắt đầu từ yêu cầu đổi dữ liệu, không phải từ sự cố mạng.','Yêu cầu mới → giao diện chưa cập nhật → API từ chối → đăng ký thất bại.','E04 và E05 cho thấy sự không tương thích đã tạo ra lỗi trong môi trường cục bộ.','Ẩn demo là quyết định tiếp theo của nhóm, không phải kết quả tự động do lỗi kỹ thuật gây ra.']},
  {id:'T03',chapter:1,concept:'NL01',kind:'relations',title:'Xác định điểm cần tác động',prompt:'Chọn hai mối liên hệ cần ưu tiên xử lý và hai điều cần theo dõi trước khi nhóm trình bày lại.',evidence:['E03','E04','E09'],hints:['Khi yêu cầu dữ liệu đổi, những phần nào trong cùng luồng phải thay đổi theo?','Một phần việc “hoàn thành” có đủ chứng minh toàn hệ thống đã hoạt động không?'],criteria:['Ưu tiên đồng bộ yêu cầu','Ưu tiên kiểm thử đầu-cuối','Theo dõi kết quả và điều kiện dự phòng','Không đánh đồng mọi yếu tố là trọng tâm'],feedback:['Yêu cầu mới cần được cập nhật đồng bộ ở các phần liên quan.','Hoàn thành từng phần chỉ có ý nghĩa khi hệ thống đã được ghép và kiểm thử.','Kết quả test và phương án chạy cục bộ là hai dữ kiện cần theo dõi trước buổi trình bày.','Trang trí giao diện hoặc đổi người trình bày không giải quyết quan hệ đang gây lỗi.']},
  {id:'T04',chapter:2,concept:'PT01',kind:'choices',title:'Từ ba trường hợp đến một nhận xét',prompt:'So sánh C-A, C-B và C-C. Tìm điểm chung có căn cứ, nhưng không bỏ qua đặc điểm riêng của từng hồ sơ.',evidence:['E10'],hints:['C-C có gặp sự cố cùng loại với C-A và C-B không?','Điểm chung cần tìm nằm ở sự không tương thích và kiểm thử, không phải ở tên lỗi.'],criteria:['Nhận diện đúng từng trường hợp','Tìm được quan hệ chung ở C-A và C-B','Phân biệt lỗi cụ thể','Không khái quát quá mức'],feedback:['Mỗi hồ sơ là một trường hợp cụ thể cần được xem xét trong hoàn cảnh riêng.','C-A và C-B cùng thiếu sự thống nhất giữa các phần và kiểm thử tích hợp.','C-A lệch trường dữ liệu, C-B gọi sai đường dẫn API; đó là những nét riêng.','Ba hồ sơ chưa cho phép kết luận mọi dự án đều sẽ thất bại như vậy.'],questions:[q('cases','C-A, C-B, C-C là gì trong phân tích này?','specific',[['common','Ba biểu hiện giống hệt nhau của một lỗi'],['specific','Ba trường hợp dự án cụ thể (cái riêng)']]),q('common','Điểm chung của C-A và C-B là gì?','incompatible',[['network','Cả hai đều thất bại vì mất mạng'],['incompatible','Các phần không tương thích và chưa được kiểm thử khi ghép chung']]),q('detail','Nét riêng cần giữ lại là gì?','field',[['field','C-A lệch trường dữ liệu, C-B sai đường dẫn API'],['person','Mỗi nhóm có một thành viên thiếu trách nhiệm']]),q('limit','Kết luận nào phù hợp nhất?','limited',[['absolute','Mọi nhóm làm dự án phần mềm đều sẽ thất bại'],['limited','Hai hồ sơ có vấn đề quy trình chung, nhưng chưa đủ để kết luận cho mọi nhóm']])]},
  {id:'T05',chapter:2,concept:'PT03',kind:'choices',title:'Nếu điều kiện bên ngoài thay đổi',prompt:'Thử thay đổi điều kiện mạng nhưng giữ nguyên dữ liệu đầu vào. Điều gì là nguyên nhân trực tiếp của lỗi, và điều gì ảnh hưởng đến quá trình xử lý?',evidence:['E04','E05','E06','E10'],hints:['Giữ nguyên dữ liệu thiếu fullName rồi bật mạng lại.','Sau đó đổi dữ liệu cho đúng và quan sát kết quả trên máy cục bộ.'],criteria:['Nhận diện nguyên nhân trực tiếp','Phân biệt vai trò của sự cố mạng','Không xem nhẹ điều kiện bên ngoài','Thấy kết quả đổi khi nguyên nhân đổi'],feedback:['Nếu dữ liệu vẫn thiếu trường bắt buộc, API vẫn từ chối dù kết nối đã ổn định.','Trong phạm vi luồng dữ liệu, mất mạng là điều kiện bên ngoài chứ không tạo ra lỗi thiếu fullName.','Sự cố mạng vẫn có nguyên nhân riêng và gây khó khăn cho việc đồng bộ, chia sẻ.','Khi dữ liệu được sửa đúng, phải đánh giá lại kết quả thay vì giữ nguyên kết luận cũ.'],questions:[q('fixed','Dữ liệu vẫn thiếu fullName nhưng mạng ổn định thì sao?','reject',[['pass','Luồng đăng ký hoàn tất bình thường'],['reject','API vẫn từ chối dữ liệu thiếu trường bắt buộc']]),q('network','Sự cố mạng giữ vai trò nào trong phạm vi này?','external',[['external','Điều kiện bên ngoài, không sinh ra lỗi quy ước dữ liệu'],['only','Nguyên nhân duy nhất khiến luồng đăng ký thất bại']]),q('impact','Có thể bỏ qua sự cố mạng không?','caused',[['ignore','Có, vì điều kiện bên ngoài không đáng quan tâm'],['caused','Không, nó làm khó việc đồng bộ và xử lý, dù không tạo lỗi dữ liệu']]),q('change','Nếu nhóm sửa đúng dữ liệu đầu vào thì sao?','conditional',[['same','Kết quả chắc chắn vẫn không đổi'],['conditional','Cần kiểm tra lại; khi nguyên nhân đổi, kết quả có thể đổi']])]},
  {id:'T06',chapter:2,concept:'PT04',kind:'report',title:'Tổ chức một báo cáo có căn cứ',prompt:'Sắp sáu mảnh thông tin thành báo cáo sự cố rõ ràng: người đọc cần thấy nguyên nhân, hệ quả, biện pháp và cách kiểm chứng theo một trật tự hợp lý.',evidence:['E12'],hints:['Mở đầu bằng yêu cầu thay đổi, rồi giải thích sự không tương thích và kết quả kiểm thử.','Hậu quả phải được nêu trước biện pháp; sau biện pháp mới đến kiểm thử lại.'],criteria:['Giữ đủ các mảnh thông tin','Mở đầu bằng chuỗi giải thích nguyên nhân','Đặt biện pháp sau hậu quả','Thấy hình thức tổ chức phục vụ nội dung'],feedback:['Sáu mảnh đều là nội dung cần thiết của báo cáo.','Yêu cầu → không tương thích → kết quả test tạo thành phần giải thích cơ chế.','Hậu quả → biện pháp → kiểm thử lại giúp người đọc thấy hướng xử lý có kiểm chứng.','Hình thức ở đây là cách tổ chức lập luận, không chỉ là cách trang trí văn bản.']},
  {id:'T07',chapter:2,concept:'QL02',kind:'choices',title:'Giải quyết mâu thuẫn trong quy trình',prompt:'Xác định hai yêu cầu đối lập trong cách nhóm vận hành, quan hệ phụ thuộc của chúng và phương án giải quyết phù hợp.',evidence:['E11','E13'],hints:['Không đồng nhất mâu thuẫn của quy trình với bất đồng giữa hai cá nhân.','Chuẩn chung giúp tích hợp; quyền chủ động giúp tiến độ linh hoạt.'],criteria:['Nhận diện đúng hai mặt đối lập','Thấy sự thống nhất của chúng','Thấy sự kìm hãm lẫn nhau','Chọn cách giải quyết có điều kiện'],feedback:['Mâu thuẫn đang xét là giữa yêu cầu chuẩn chung và yêu cầu chủ động trong thực hiện.','Chuẩn chung cần cho việc ghép hệ thống; chủ động cần để từng phần không bị tắc nghẽn.','Tập trung phê duyệt quá mức làm chậm tiến độ, còn tự do hoàn toàn làm khó tích hợp.','Phương án phù hợp là phân quyền theo phạm vi, giữ chuẩn chung và kiểm thử liên mô-đun.'],questions:[q('opposites','Hai mặt đối lập trong quy trình là gì?','standard',[['people','Mâu thuẫn giữa Nam và Mai'],['standard','Yêu cầu chuẩn chung và yêu cầu chủ động, linh hoạt']]),q('unity','Vì sao hai mặt này vẫn cần nhau?','depend',[['depend','Cần chuẩn để tích hợp, cần chủ động để xử lý từng phần linh hoạt'],['none','Chúng không có bất kỳ quan hệ nào']]),q('conflict','Sự kìm hãm biểu hiện ở đâu?','change',[['argue','Chỉ ở việc các thành viên tranh luận'],['change','Kiểm soát quá chặt làm chậm tiến độ; tự do quá mức làm vỡ chuẩn chung']]),q('solution','Phương án giải quyết phù hợp là gì?','delegate',[['silence','Loại tất cả thành viên khỏi dự án'],['delegate','Phân quyền theo phạm vi, giữ quy ước và kiểm thử chung'],['remove','Bỏ toàn bộ chuẩn chung để làm nhanh']])]},
  {id:'T08',chapter:3,concept:'QL01',kind:'choices',title:'Khi nào thay đổi lượng tạo ra chất mới?',prompt:'Dùng mô hình A → D để phân biệt số lượng liên kết với khả năng vận hành của cả luồng. Hãy thử các cách nối và quan sát kết quả.',evidence:['E14'],hints:['Thử C→A trước: hệ thống có đi được từ B sang C không?','Thử B→C và quan sát đường đi tới D.'],criteria:['Xác định lượng đang xét','Xác định chất mới của hệ thống','Thấy vai trò của cấu trúc','Phân biệt điều kiện với chuyển hóa'],feedback:['Trong mô hình này, số liên kết là mặt lượng đang được đếm.','Chất mới là luồng từ A đến D hoạt động thông suốt.','Liên kết chỉ có tác dụng khi được đặt trong cấu trúc phù hợp; không có một con số chung cho mọi hệ thống.','Có liên kết cần thiết là điều kiện; luồng vận hành thông suốt là kết quả thay đổi về chất trong mô hình.'],questions:[q('quantity','Mặt “lượng” đang được xét là gì?','links',[['points','Số điểm kinh nghiệm của người lập trình'],['links','Số liên kết được tạo trong mô hình']]),q('quality','“Chất” mới của mô hình là gì?','flow',[['flow','Luồng xử lý đi thông từ A đến D'],['pretty','Giao diện của mô hình đẹp hơn']]),q('structure','Hai cách nối cho thấy điều gì?','right',[['any','Chỉ cần thêm đủ số liên kết là hệ thống sẽ chạy'],['right','Thêm yếu tố sai cấu trúc không tạo ra luồng hoạt động']]),q('transition','Diễn giải nào phù hợp nhất?','process',[['instant','Mỗi liên kết mới tự động tạo một hệ thống hoàn toàn mới'],['process','Liên kết đúng là điều kiện; luồng thông suốt biểu hiện sự chuyển hóa về chất']])]},
  {id:'T09',chapter:3,concept:'QL03',kind:'choices',title:'Thiết kế quy trình A′',prompt:'Chọn phương án mới kế thừa được ưu điểm và khắc phục hạn chế của A, B. A′ không phải sự lặp lại nguyên trạng của A.',evidence:['E11','E13','E15'],hints:['A′ cần tránh cả việc thiếu chuẩn của A lẫn điểm nghẽn của B.','Đổi mới có kế thừa khác với xóa sạch và làm lại từ đầu.'],criteria:['Chọn đúng phương án A′','Kế thừa ưu điểm của A','Kế thừa ưu điểm của B','Không quay lại trạng thái cũ'],feedback:['A′ kết hợp quyền chủ động theo phạm vi với quy ước chung và kiểm thử liên mô-đun.','Từ A có thể giữ sự chủ động và tốc độ xử lý phần việc.','Từ B có thể giữ quy ước, nhật ký và cơ chế kiểm soát chất lượng.','A′ trở lại một số yếu tố của A trên cơ sở đã cải biến, nên không đồng nhất với A.'],questions:[q('model','Phương án A′ nên tổ chức thế nào?','adaptive',[['free','Mỗi người tự làm, không cần bất kỳ quy ước nào'],['central','Một người duyệt mọi thay đổi của cả nhóm'],['adaptive','Tự quản phạm vi phụ trách, tuân thủ chuẩn chung và kiểm thử liên tục']]),q('fromA','Yếu tố nào từ A còn phù hợp để kế thừa?','autonomy',[['autonomy','Sự chủ động trong phạm vi phần việc'],['inconsistent','Cách tích hợp không thống nhất']]),q('fromB','Yếu tố nào từ B cần được giữ lại?','standards',[['queue','Việc mọi thay đổi phải chờ một người duyệt'],['standards','Quy ước chung và hệ thống nhật ký']]),q('return','A′ có phải A được lặp lại nguyên trạng không?','higher',[['same','Đúng, chỉ đổi tên quy trình'],['higher','Không, A′ kế thừa nhưng đã cải biến ở trình độ tổ chức mới']])]},
  {id:'T10',chapter:3,concept:'NL02',kind:'choices',title:'Bản cập nhật nào là phát triển thực sự?',prompt:'Đánh giá ba bản xây dựng bằng khả năng giải quyết nhiệm vụ cốt lõi. Đừng chỉ dựa vào số tính năng hoặc diện mạo.',evidence:['E16'],hints:['V1 và V2 có giải quyết được luồng đăng ký không?','V3 mới qua kiểm thử cục bộ; điều đó nói gì về giới hạn của kết luận?'],criteria:['Phân biệt thay đổi bề ngoài','Nhận diện mở rộng không trọng tâm','Đánh giá tiến bộ ở nhiệm vụ cốt lõi','Nêu giới hạn của kiểm thử'],feedback:['V1 chỉ đổi biểu hiện bên ngoài, còn lỗi dữ liệu vẫn tồn tại.','V2 có thêm chức năng phụ nhưng không thay đổi luồng đang thất bại.','V3 sửa đúng quan hệ dữ liệu và qua kiểm thử đã nêu, cho thấy bước tiến trong phạm vi đó.','Kết quả cục bộ chưa bảo đảm mọi môi trường thực tế đều hoạt động như nhau.'],questions:[q('v1','V1 chỉ thay hiệu ứng giao diện. Đánh giá nào phù hợp?','presentation',[['progress','Đó chắc chắn là phát triển của luồng đăng ký'],['presentation','Đó là thay đổi cách thể hiện, chưa giải quyết lỗi cốt lõi']]),q('v2','V2 thêm giao diện tối và nút chia sẻ. Điều gì cần lưu ý?','expansion',[['expansion','Mở rộng tính năng không đồng nghĩa luồng chính đã hoạt động'],['best','Nhiều tính năng hơn luôn là bản tốt nhất']]),q('v3','V3 sửa dữ liệu và kiểm thử lại. Kết luận nào hợp lý?','capability',[['cosmetic','V3 không có giá trị vì ít thay đổi hình thức'],['capability','V3 phát triển năng lực thực hiện luồng cốt lõi trong điều kiện đã kiểm thử']]),q('limit','Có thể khẳng định V3 chắc chắn thành công ở mọi nơi không?','limited',[['guarantee','Có, vì chạy trên một máy là đủ'],['limited','Không, cần tiếp tục kiểm tra trong các điều kiện khác']])]},
  {id:'T11',chapter:3,concept:'PT06',kind:'recovery',title:'Từ khả năng đến kết quả',prompt:'Lập kế hoạch 60 phút để khôi phục một bản demo giới hạn. Chọn việc cần thiết, xếp đúng điều kiện trước–sau và nêu giới hạn của kết quả.',evidence:['E17'],hints:['Chưa chốt yêu cầu dữ liệu thì chưa thể viết đúng bước chuyển đổi.','Bốn việc cốt lõi mất 55 phút; cần ưu tiên điều kiện để luồng hoạt động.'],criteria:['Nhận diện các tiền đề đang có','Chọn các bước tạo điều kiện thực hiện','Sắp đúng trình tự phụ thuộc','Phân biệt demo giới hạn với sản phẩm hoàn chỉnh'],feedback:['Mã nguồn, bản sao lưu, dữ liệu mẫu và người thực hiện là những điều kiện hiện có.','Chốt yêu cầu → chuyển đổi dữ liệu → kiểm thử → chuẩn bị bản chạy tạo điều kiện cho phương án thành hiện thực.','Chuỗi A1 → A2 → A3 → A4 cần 55 phút, để lại 5 phút dự phòng.','Bản demo hoạt động trong phạm vi đã kiểm thử không đồng nghĩa với sản phẩm sẵn sàng triển khai rộng rãi.']}
];

/** Phản biện xuất hiện sau một lập luận chưa đủ vững; không tiết lộ đáp án trực tiếp. */
export const counterpoints:Record<string,{speaker:string;role:string;evidence:string;message:string}>={
  T01:{speaker:'Mai',role:'Trưởng nhóm',evidence:'E08',message:'“Trước khi kết luận ai đó đã xóa dự án, hãy kiểm tra thao tác được ghi nhận trong nhật ký trạng thái.”'},
  T02:{speaker:'Quân',role:'Phụ trách kiểm thử',evidence:'E05',message:'“Hãy quay lại lần kiểm thử cục bộ. Lỗi nào đã xuất hiện trước khi điều kiện mạng thay đổi?”'},
  T03:{speaker:'Linh',role:'Điều phối trình bày',evidence:'E09',message:'“Một phần việc hoàn thành riêng lẻ chưa đủ để tôi xác nhận bản demo có thể trình bày.”'},
  T04:{speaker:'Quân',role:'Phụ trách kiểm thử',evidence:'E10',message:'“Ba hồ sơ có điểm chung, nhưng hãy giữ lại hoàn cảnh riêng trước khi khái quát thành một kết luận lớn.”'},
  T05:{speaker:'Quân',role:'Phụ trách kiểm thử',evidence:'E05',message:'“Nếu chỉ thay trạng thái mạng mà giữ nguyên dữ liệu đầu vào, kết quả kiểm thử cục bộ sẽ nói gì?”'},
  T06:{speaker:'Linh',role:'Điều phối trình bày',evidence:'E12',message:'“Báo cáo cần để người đọc theo được quan hệ giữa nguyên nhân, hậu quả, biện pháp và kiểm thử; đừng chỉ xếp các mảnh thông tin cạnh nhau.”'},
  T07:{speaker:'Mai',role:'Trưởng nhóm',evidence:'E13',message:'“Đừng biến đây thành mâu thuẫn giữa hai người. Vấn đề là hai yêu cầu nào trong cùng một quy trình?”'},
  T08:{speaker:'Hệ thống mô phỏng',role:'Kiểm tra cấu trúc',evidence:'E14',message:'“Thêm một liên kết chưa nói lên điều gì nếu liên kết ấy không tạo được đường đi từ đầu vào đến kết quả.”'},
  T09:{speaker:'Mai',role:'Trưởng nhóm',evidence:'E15',message:'“Phương án mới cần giữ lại điều còn phù hợp, đồng thời khắc phục điểm nghẽn cũ. Hãy so sánh cả A, B và A′.”'},
  T10:{speaker:'Quân',role:'Phụ trách kiểm thử',evidence:'E16',message:'“Trước khi gọi một bản cập nhật là tiến bộ, hãy hỏi: nó có làm luồng cốt lõi hoạt động tốt hơn trong điều kiện đã kiểm tra không?”'},
  T11:{speaker:'Hệ thống mô phỏng',role:'Kiểm tra điều kiện',evidence:'E17',message:'“Một kế hoạch chỉ có thể thực hiện khi các điều kiện phụ thuộc được đáp ứng theo đúng thứ tự.”'}
};
