const fs = require('fs');
let code = fs.readFileSync('components/Game.tsx', 'utf8');

const original = `<h3>Chứng cứ đã ghim</h3><div className="pinned-grid">{state.pinned.map(id=>{const e=evidence.find(e=>e.id===id)!;return <button key={id} onClick={()=>choose(id)}><span>{id}<Pin size={14}/></span><strong>{e.title}</strong><p>{e.summary}</p></button>;})}{!state.pinned.length&&<p className="muted">Mở chứng cứ rồi chọn “Ghim chứng cứ” để đặt lên bảng.</p>}</div><h3>Lịch sử lập luận</h3>{tasks.filter(t=>state.answers[t.id]).map(t=>{const score=evaluateChallenge(t.id,state.answers[t.id]).score;return <div className="claim-card" key={t.id}><button onClick={()=>dispatch({type:'task',id:t.id})}><span>{t.id} · {score===4?'Có căn cứ':'Cần bổ sung'}</span><strong>{t.title}</strong><ArrowRight size={17}/></button><p>{state.attempts[t.id]?.length??0} lần ghi nhận · lần đầu {state.attempts[t.id]?.[0].evaluation.score??0}/4 → hiện tại {score}/4</p>{state.notes[t.id]&&<blockquote>{state.notes[t.id]}</blockquote>}</div>;})}{!Object.keys(state.answers).length&&<p className="muted">Các lập luận xuất hiện ở đây sau khi được ghi nhận.</p>}`;

const replacement = `<div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:'40px', alignItems:'start'}}><div><h3>Chứng cứ đã ghim</h3><div className="pinned-grid">{state.pinned.map(id=>{const e=evidence.find(e=>e.id===id)!;return <button key={id} onClick={()=>choose(id)}><span>{id}<Pin size={14}/></span><strong>{e.title}</strong><p>{e.summary}</p></button>;})}{!state.pinned.length&&<p className="muted">Mở chứng cứ rồi chọn “Ghim chứng cứ” để đặt lên bảng.</p>}</div></div><div><h3>Lịch sử lập luận</h3><div className="claim-list" style={{display:'flex', flexDirection:'column', gap:'15px'}}>{tasks.filter(t=>state.answers[t.id]).map(t=>{const score=evaluateChallenge(t.id,state.answers[t.id]).score;return <div className="claim-card" key={t.id}><button onClick={()=>dispatch({type:'task',id:t.id})}><span>{t.id} · {score===4?'Có căn cứ':'Cần bổ sung'}</span><strong>{t.title}</strong><ArrowRight size={17}/></button><p>{state.attempts[t.id]?.length??0} lần ghi nhận · lần đầu {state.attempts[t.id]?.[0].evaluation.score??0}/4 → hiện tại {score}/4</p>{state.notes[t.id]&&<blockquote>{state.notes[t.id]}</blockquote>}</div>;})}{!Object.keys(state.answers).length&&<p className="muted">Các lập luận xuất hiện ở đây sau khi được ghi nhận.</p>}</div></div></div>`;

code = code.replace(original, replacement);
fs.writeFileSync('components/Game.tsx', code);
