import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
import {completeState,perfect} from '../fixtures';
import {tasks,chainOptions,reportOptions,relationOptions,recoveryActions} from '../../game/tasks';
import {createState,reduceGame} from '../../game/engine';
import type {GameState,Answer} from '../../game/types';
mkdirSync('outputs/qa',{recursive:true});
async function seed(page:Page,s:GameState){await page.addInitScript(state=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem(`hsdc:save:${state.mode}:v1`,JSON.stringify(state));localStorage.setItem('hsdc:settings:v1',JSON.stringify({mode:state.mode,reduced:true}));sessionStorage.setItem('seeded','1');}},s);await page.goto('/');}
async function begin(page:Page){await page.goto('/');await page.getByRole('button',{name:'Mở hồ sơ',exact:true}).click();await page.getByRole('radio',{name:'Nam đã xóa hoặc phá demo.',exact:true}).check();await page.getByRole('radio',{name:'Cao',exact:true}).check();await page.getByRole('button',{name:'Bắt đầu điều tra',exact:true}).click();await expect(page.getByRole('heading',{name:'Điều gì thực sự xảy ra?',exact:true})).toBeVisible();}
async function fillTask(page:Page,id:string,a:Answer){
 const panel=page.getByRole('complementary',{name:'Nhiệm vụ điều tra'});const task=tasks.find(t=>t.id===id)!;
 await page.getByRole('button',{name:`Nhiệm vụ ${id}`,exact:true}).click();
 const radio=async(text:string)=>{await panel.getByRole('radio',{name:text,exact:true}).check();};
 switch(a.kind){
 case 'classify':{const values=Object.values(a.categories);for(let i=0;i<4;i++)await panel.getByRole('combobox').nth(i).selectOption(values[i]);for(const ev of a.evidence)await panel.getByRole('button',{name:new RegExp(`^${ev} ·`)}).click();break;}
 case 'chain':for(const v of a.order)await panel.getByRole('button',{name:chainOptions.find(o=>o.id===v)!.label,exact:true}).click();for(const ev of a.evidence)await panel.getByRole('button',{name:new RegExp(`^${ev} ·`)}).click();await radio('Lỗi chưa khắc phục là căn cứ cho quyết định rút demo tiếp theo.');break;
 case 'relations':for(const v of a.priority)await panel.getByRole('group',{name:'Hai quan hệ ưu tiên',exact:false}).getByRole('button',{name:relationOptions.find(o=>o.id===v)!.label,exact:true}).click();for(const v of a.monitor)await panel.getByRole('group',{name:'Hai quan hệ theo dõi',exact:false}).getByRole('button',{name:relationOptions.find(o=>o.id===v)!.label,exact:true}).click();await radio('Sát giờ trình diễn: khôi phục luồng cốt lõi và xác nhận điều kiện.');break;
 case 'choices':for(const q of task.questions!)await radio(q.options.find(o=>o.id===a.values[q.id])!.label);break;
 case 'report':for(const v of a.order)await panel.getByRole('button',{name:reportOptions.find(o=>o.id===v)!.label,exact:true}).click();await radio('Bố cục và liên kết giữa các phần giúp làm rõ nội dung.');break;
 case 'recovery':await radio('Mã, bản lưu, dữ liệu thử và thành viên đã có. Demo còn cần thực hiện.');for(const v of a.order){const o=recoveryActions.find(o=>o.id===v)!;await panel.getByRole('button',{name:`${v} · ${o.label} (${o.minutes}′)`,exact:true}).click();}await radio('Demo giới hạn được thực hiện trong điều kiện mô phỏng; cần kiểm tra thêm để khai thác thật.');break;
 }
 if(id==='T05'){await panel.getByRole('button',{name:'Chạy lại mô hình'}).click();await expect(panel.getByText('Local: từ chối',{exact:true})).toBeVisible();await panel.getByRole('checkbox',{name:'Đã chuyển đổi dữ liệu'}).check();await panel.getByRole('button',{name:'Chạy lại mô hình'}).click();await expect(panel.getByText('Local: hoàn tất',{exact:true})).toBeVisible();}
 if(id==='T08'){await panel.getByRole('button',{name:'Thử C → A'}).click();await expect(panel.getByText('A → B → A · chưa tới D',{exact:true})).toBeVisible();await panel.getByRole('button',{name:'Thử B → C'}).click();await expect(panel.getByText('A → B → C → D',{exact:true})).toBeVisible();}
 if(id==='T10'){for(const v of ['V1','V2','V3']){await panel.getByRole('button',{name:v,exact:true}).click();await panel.getByRole('button',{name:`Chạy bản ${v}`,exact:true}).click();}}
 if(id==='T11'){await panel.getByRole('button',{name:'Mô phỏng phương án'}).click();await expect(panel.getByText(/demo giới hạn qua kiểm thử/)).toBeVisible();}
 await panel.getByRole('button',{name:'Ghi nhận lập luận',exact:true}).click();await expect(panel.getByText('4/4 tiêu chí có căn cứ',{exact:true})).toBeVisible();
}
test('A: toàn bộ lượt chơi qua UI, nguồn, mô phỏng và kết thúc 4',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await begin(page);
 await page.getByRole('button',{name:/E07.*Nhóm Mạch Nối/}).first().click();await expect(page.getByText('Tôi không làm tiếp nữa nếu vẫn đổi dữ liệu', {exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Ghim chứng cứ',exact:true}).click();await expect(page.getByRole('button',{name:'Đã ghim',exact:true})).toBeVisible();
 for(const t of tasks){await fillTask(page,t.id,perfect[t.id]);if(['T03','T07','T11'].includes(t.id)){await page.getByRole('button',{name:`Giải mã chương ${t.chapter}`,exact:true}).click();await expect(page.getByText(`GIẢI MÃ CHƯƠNG 0${t.chapter}`,{exact:true})).toBeVisible();await page.getByRole('button',{name:t.chapter===3?'Viết kết luận cuối':'Mở chương tiếp theo',exact:true}).click();}}
 await page.getByRole('radio',{name:/Nhóm chủ động rút luồng chưa đạt/}).check();for(const id of ['E08','E05','E04','E07'])await page.getByRole('button',{name:new RegExp(`^${id} ·`)}).click();await page.getByLabel('Ghi chú kết luận',{exact:false}).fill('Kết luận thay đổi sau khi đối chiếu kiểm thử và nhật ký.');await page.getByRole('button',{name:'Chốt hồ sơ',exact:true}).click();await expect(page.getByRole('heading',{name:'Đảo chiều có căn cứ',exact:true})).toBeVisible();await expect(page.getByText('44/44 tiêu chí',{exact:false})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Đảo chiều có căn cứ',exact:true})).toBeVisible();expect(errors).toEqual([]);await page.screenshot({path:'outputs/qa/result.png',fullPage:true});
});
test('B: kết luận quy kết Nam dẫn tới kết thúc 1',async({page})=>{await seed(page,completeState());await page.getByRole('radio',{name:'Nam cố ý phá demo.',exact:true}).check();await page.getByRole('button',{name:/^E01 ·/}).click();await page.getByRole('button',{name:'Chốt hồ sơ',exact:true}).click();await expect(page.getByRole('heading',{name:'Khép hồ sơ quá sớm',exact:true})).toBeVisible();await expect(page.getByText(/Mai thực hiện thao tác ẩn/)).toBeVisible();});
test('C: quá thời gian dẫn tới kết thúc 3; điểm không lấy từ storage',async({page})=>{const s=completeState();s.answers.T11={kind:'recovery',order:['A1','A2','A3','A4','A6'],reality:'available',conclusion:'limited'};await seed(page,s);await page.getByRole('radio',{name:/Nhóm chủ động rút luồng chưa đạt/}).check();for(const id of ['E08','E05','E04','E07'])await page.getByRole('button',{name:new RegExp(`^${id} ·`)}).click();await page.getByRole('button',{name:'Chốt hồ sơ',exact:true}).click();await expect(page.getByRole('heading',{name:'Đúng nguyên nhân, chưa hoàn tất chuyển biến',exact:true})).toBeVisible();});
test('D: reload giữa chương 2 giữ đáp án và ghi chú',async({page})=>{let s=completeState();s=reduceGame(s,{type:'chapter',chapter:2});await seed(page,s);await page.getByRole('button',{name:'Nhiệm vụ T04',exact:true}).click();await page.getByText('Ghi chú riêng',{exact:false}).click();await page.getByRole('textbox',{name:'Ghi chú riêng',exact:true}).fill('C-C là trường hợp đối chiếu khác.');await expect.poll(async()=>page.evaluate(()=>JSON.parse(localStorage.getItem('hsdc:save:individual:v1')!).notes.T04)).toBe('C-C là trường hợp đối chiếu khác.');await page.reload();await expect(page.getByRole('heading',{name:'Ba sự cố, điều gì chung?',exact:true})).toBeVisible();await expect(page.getByRole('radio',{name:'Ba trường hợp cụ thể — những cái riêng',exact:true})).toBeChecked();});
test('E: trang đầu, email, chat, nhật ký và mobile không tràn ngang',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:/Mọi dấu vết/})).toBeVisible();await page.screenshot({path:'outputs/qa/landing-desktop.png',fullPage:true});await begin(page);
 await page.getByRole('button',{name:/E02.*Ban tổ chức/}).first().click();await expect(page.getByText('<trienlam@machnoi.example>',{exact:true})).toBeVisible();await page.screenshot({path:'outputs/qa/email-desktop.png',fullPage:true});
 await page.getByRole('button',{name:/E07.*Nhóm Mạch Nối/}).first().click();await page.screenshot({path:'outputs/qa/chat-desktop.png',fullPage:true});
 await page.getByRole('button',{name:/E05.*Nam/}).first().click();await expect(page.getByText('Missing required field: fullName',{exact:false})).toBeVisible();await page.screenshot({path:'outputs/qa/log-desktop.png',fullPage:true});
 for(const width of [390,360]){await page.setViewportSize({width,height:844});await expect.poll(async()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Lập luận',exact:true}).click();await expect(page.getByRole('heading',{name:'Bạn thực sự biết điều gì?',exact:true})).toBeVisible();await page.getByRole('button',{name:'Chứng cứ',exact:true}).click();await page.getByRole('button',{name:/E07.*Nhóm Mạch Nối/}).first().click();await expect(page.getByText('Tôi không làm tiếp nữa nếu vẫn đổi dữ liệu',{exact:false})).toBeVisible();await expect.poll(async()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`outputs/qa/mobile-${width}.png`,fullPage:true});}
});
test('F: trình chiếu và cá nhân dùng bản lưu riêng',async({page})=>{let s=createState('presenter');s=reduceGame(s,{type:'begin',conclusion:'unknown',confidence:'Thấp'});await seed(page,s);await page.setViewportSize({width:1920,height:1080});await expect(page.getByText(/Chế độ trình chiếu · một máy/)).toBeVisible();await page.getByRole('button',{name:'Dừng để thảo luận'}).click();await expect(page.getByRole('button',{name:'Tiếp tục',exact:true})).toBeVisible();await page.screenshot({path:'outputs/qa/presenter.png',fullPage:true});await page.getByRole('button',{name:'Tùy chọn',exact:true}).click();await page.getByRole('button',{name:'Chuyển sang cá nhân',exact:true}).click();await expect(page.getByRole('button',{name:'Mở hồ sơ',exact:true})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('hsdc:save:presenter:v1')!).initial.confidence)).toBe('Thấp');});
test('G: bản lưu hỏng không bị tự ghi đè',async({page})=>{await page.addInitScript(()=>localStorage.setItem('hsdc:save:individual:v1','{invalid'));await page.goto('/');await expect(page.getByRole('alert')).toContainText('lưu đang tạm dừng');expect(await page.evaluate(()=>localStorage.getItem('hsdc:save:individual:v1'))).toBe('{invalid');});
test('H: tab thứ hai cập nhật thì tab cũ dừng ghi',async({page,context})=>{const s=reduceGame(createState(),{type:'begin',conclusion:'unknown',confidence:'Vừa'});await seed(page,s);const other=await context.newPage();await other.goto('/');await other.getByRole('button',{name:/E07.*Nhóm Mạch Nối/}).first().click();await expect(page.getByRole('alert')).toContainText('lưu đang tạm dừng');await page.getByRole('button',{name:'Tải bản mới nhất',exact:true}).click();await expect(page.getByText('Tôi không làm tiếp nữa nếu vẫn đổi dữ liệu',{exact:false})).toBeVisible();await other.close();});
