import {env} from 'cloudflare:workers';
import {applyCompetitionAction,CINEMATIC_SECONDS,COMPETITION_SCORING_VERSION,scoreAction,type LeaderboardEntry,type RoomSnapshot} from '../game/competition';
import {createState} from '../game/engine';
import {getConfig} from '../game/config';
import type {Action,Difficulty,GameState} from '../game/types';

const COOKIE='hsdc_comp_session';
const encoder=new TextEncoder();
let initialized:Promise<void>|null=null;
const db=()=>{if(!env.DB)throw new Error('D1 binding DB is unavailable');return env.DB;};
const now=()=>Date.now();
const json=(data:unknown,status=200,headers?:HeadersInit)=>Response.json(data,{status,headers});
export class ApiError extends Error{constructor(public status:number,message:string){super(message);}}
const normalize=(s:string)=>s.trim().replace(/\s+/g,' ').toLocaleLowerCase('vi');
const token=()=>`${crypto.randomUUID()}${crypto.randomUUID().replaceAll('-','')}`;
async function sha(value:string){const out=await crypto.subtle.digest('SHA-256',encoder.encode(value));return [...new Uint8Array(out)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function cookieValue(request:Request){const part=request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${COOKIE}=`));return part?decodeURIComponent(part.slice(COOKIE.length+1)):null;}
const cookieHeader=(value:string)=>`${COOKIE}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=86400`;

async function init(){
 if(initialized)return initialized;
 initialized=(async()=>{const d=db();await d.batch([
  d.prepare('CREATE TABLE IF NOT EXISTS competition_rooms (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT \'lobby\', difficulty TEXT NOT NULL, chapter_count INTEGER NOT NULL DEFAULT 3, duration_seconds INTEGER NOT NULL, max_players INTEGER NOT NULL, case_version TEXT NOT NULL, scoring_version INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, starts_at INTEGER, play_starts_at INTEGER, ends_at INTEGER, end_reason TEXT, revision INTEGER NOT NULL DEFAULT 0)'),
  d.prepare('CREATE TABLE IF NOT EXISTS competition_members (id TEXT PRIMARY KEY, room_id TEXT NOT NULL REFERENCES competition_rooms(id) ON DELETE CASCADE, role TEXT NOT NULL, name TEXT NOT NULL, normalized_name TEXT NOT NULL, session_hash TEXT NOT NULL UNIQUE, join_order INTEGER NOT NULL, joined_at INTEGER NOT NULL, last_seen_at INTEGER NOT NULL, ready INTEGER NOT NULL DEFAULT 0, initial_conclusion TEXT, initial_confidence TEXT, game_state TEXT, version INTEGER NOT NULL DEFAULT 0, score INTEGER NOT NULL DEFAULT 0, score_updated_at INTEGER, completed_at INTEGER, ending INTEGER, UNIQUE(room_id, normalized_name))'),
  d.prepare('CREATE TABLE IF NOT EXISTS competition_actions (id TEXT PRIMARY KEY, member_id TEXT NOT NULL REFERENCES competition_members(id) ON DELETE CASCADE, expected_version INTEGER NOT NULL, processed INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL)'),
  d.prepare('CREATE TABLE IF NOT EXISTS competition_score_events (id TEXT PRIMARY KEY, room_id TEXT NOT NULL REFERENCES competition_rooms(id) ON DELETE CASCADE, member_id TEXT NOT NULL REFERENCES competition_members(id) ON DELETE CASCADE, action_id TEXT NOT NULL REFERENCES competition_actions(id) ON DELETE CASCADE, event_key TEXT NOT NULL, kind TEXT NOT NULL, reference TEXT NOT NULL, delta INTEGER NOT NULL, created_at INTEGER NOT NULL, UNIQUE(member_id,event_key))'),
  d.prepare('CREATE INDEX IF NOT EXISTS idx_competition_rooms_status_expiry ON competition_rooms(status,expires_at)'),
  d.prepare('CREATE INDEX IF NOT EXISTS idx_competition_members_room_role ON competition_members(room_id,role)'),
  d.prepare('CREATE INDEX IF NOT EXISTS idx_competition_score_room_member ON competition_score_events(room_id,member_id)')
 ]);const columns=(await d.prepare('PRAGMA table_info(competition_rooms)').all<{name:string}>()).results;if(!columns.some(column=>column.name==='chapter_count'))await d.prepare('ALTER TABLE competition_rooms ADD COLUMN chapter_count INTEGER NOT NULL DEFAULT 3').run();await d.prepare("UPDATE competition_rooms SET chapter_count=2 WHERE difficulty='easy' AND chapter_count>2").run();})();
 return initialized;
}

type RoomRow={id:string;code:string;status:string;difficulty:Difficulty;chapter_count:number;duration_seconds:number;max_players:number;starts_at:number|null;play_starts_at:number|null;ends_at:number|null;end_reason:string|null;expires_at:number};
type MemberRow={id:string;room_id:string;role:'host'|'player';name:string;ready:number;last_seen_at:number;initial_conclusion:string|null;initial_confidence:string|null;game_state:string|null;version:number;score:number;score_updated_at:number|null;completed_at:number|null;ending:number|null;join_order:number};

async function auth(request:Request,roomId?:string){
 await init();const raw=cookieValue(request);if(!raw)throw new ApiError(401,'Phiên phòng không tồn tại.');
 const hash=await sha(raw);const member=await db().prepare('SELECT * FROM competition_members WHERE session_hash=?').bind(hash).first<MemberRow>();
 if(!member||(roomId&&member.room_id!==roomId))throw new ApiError(403,'Phiên phòng không hợp lệ.');
 return member;
}
async function progressRoom(roomId:string){
 const d=db(),t=now();const room=await d.prepare('SELECT * FROM competition_rooms WHERE id=?').bind(roomId).first<RoomRow>();if(!room)return;
 if(room.status==='lobby'&&t>=room.expires_at)await d.prepare("UPDATE competition_rooms SET status='cancelled',ends_at=?,end_reason='expired',revision=revision+1 WHERE id=? AND status='lobby'").bind(t,roomId).run();
 if(room.status==='countdown'&&room.play_starts_at&&t>=room.play_starts_at)await d.prepare("UPDATE competition_rooms SET status='playing',revision=revision+1 WHERE id=? AND status='countdown'").bind(roomId).run();
 if((room.status==='playing'||room.status==='countdown')&&room.ends_at&&t>=room.ends_at)await d.prepare("UPDATE competition_rooms SET status='finished',ends_at=?,end_reason='timeout',revision=revision+1 WHERE id=? AND status IN ('playing','countdown')").bind(room.ends_at,roomId).run();
 const counts=await d.prepare("SELECT COUNT(*) total,SUM(CASE WHEN completed_at IS NOT NULL THEN 1 ELSE 0 END) completed FROM competition_members WHERE room_id=? AND role='player'").bind(roomId).first<{total:number;completed:number}>();
 if(counts&&counts.total>0&&counts.completed===counts.total)await d.prepare("UPDATE competition_rooms SET status='finished',ends_at=COALESCE(ends_at,?),end_reason='all_completed',revision=revision+1 WHERE id=? AND status IN ('playing','countdown')").bind(t,roomId).run();
}
async function snapshot(roomId:string,me:MemberRow):Promise<RoomSnapshot>{
 await progressRoom(roomId);const d=db();
 const room=await d.prepare('SELECT * FROM competition_rooms WHERE id=?').bind(roomId).first<RoomRow>();if(!room)throw new ApiError(404,'Không tìm thấy phòng.');
 const members=(await d.prepare('SELECT * FROM competition_members WHERE room_id=? ORDER BY join_order').bind(roomId).all<MemberRow>()).results;
 const eventRows=(await d.prepare('SELECT member_id,kind,COUNT(*) count FROM competition_score_events WHERE room_id=? GROUP BY member_id,kind').bind(roomId).all<{member_id:string;kind:string;count:number}>()).results;
 const stats=new Map<string,Record<string,number>>();for(const e of eventRows){const s=stats.get(e.member_id)??{};s[e.kind]=e.count;stats.set(e.member_id,s);}
 const started=room.play_starts_at??room.starts_at??room.expires_at;
 const players=members.filter(m=>m.role==='player');
 const sorted=[...players].sort((a,b)=>b.score-a.score||((a.completed_at??a.score_updated_at??started)-(b.completed_at??b.score_updated_at??started))||a.join_order-b.join_order);
 let previous:MemberRow|null=null,rank=0;
 const leaderboard:LeaderboardEntry[]=sorted.map((m,i)=>{const tie=m.completed_at??m.score_updated_at??started;if(!previous||previous.score!==m.score||(previous.completed_at??previous.score_updated_at??started)!==tie)rank=i+1;previous=m;const s=stats.get(m.id)??{};return {id:m.id,name:m.name,score:m.score,rank,ready:!!m.ready,connected:now()-m.last_seen_at<15000,completedAt:m.completed_at,scoreUpdatedAt:m.score_updated_at,ending:m.ending,tieTime:Math.max(0,tie-started),stats:{evidence:s.evidence??0,criteria:s.criterion??0,tasks:s.task??0,chapters:s.chapter??0,hints:s.hint??0,evidenceHints:s.evidenceHint??0,wrong:s.wrong??0,submissions:s.submission??0}};});
 return {id:room.id,code:room.code,status:room.status as RoomSnapshot['status'],role:me.role,difficulty:room.difficulty,chapterCount:room.chapter_count,durationSeconds:room.duration_seconds,maxPlayers:room.max_players,startsAt:room.starts_at,playStartsAt:room.play_starts_at,endsAt:room.ends_at,serverNow:now(),endReason:room.end_reason,members:members.map(m=>({id:m.id,name:m.name,role:m.role,ready:!!m.ready,connected:now()-m.last_seen_at<15000})),leaderboard,me:{id:me.id,name:me.name,ready:!!me.ready,version:me.version,score:me.score,state:me.game_state?JSON.parse(me.game_state) as GameState:null,initial:me.initial_conclusion&&me.initial_confidence?{conclusion:me.initial_conclusion,confidence:me.initial_confidence}:null}};
}

export async function createRoom(request:Request){
 await init();const body=await request.json() as {difficulty?:Difficulty;chapterCount?:number;durationMinutes?:number;maxPlayers?:number};const difficulty=body.difficulty==='easy'?'easy':'standard';const maxChapter=getConfig(difficulty).lastChapter,chapterCount=Math.round(Number(body.chapterCount??maxChapter));const duration=Math.round(Number(body.durationMinutes??15));const max=Math.round(Number(body.maxPlayers??10));if(!Number.isInteger(chapterCount)||chapterCount<1||chapterCount>maxChapter)throw new ApiError(400,`Số chương phải từ 1 đến ${maxChapter}.`);if(duration<5||duration>60||duration%5)throw new ApiError(400,'Thời gian phải từ 5 đến 60 phút, theo bước 5 phút.');if(max<2||max>30)throw new ApiError(400,'Số người chơi phải từ 2 đến 30.');
 const raw=token(),hash=await sha(raw),roomId=crypto.randomUUID(),hostId=crypto.randomUUID(),t=now();let code='';
 for(let attempt=0;attempt<20;attempt++){code=String(crypto.getRandomValues(new Uint32Array(1))[0]%10000).padStart(4,'0');try{await db().batch([db().prepare('INSERT INTO competition_rooms (id,code,status,difficulty,chapter_count,duration_seconds,max_players,case_version,scoring_version,created_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(roomId,code,'lobby',difficulty,chapterCount,duration*60,max,'1.1.0',COMPETITION_SCORING_VERSION,t,t+7200000),db().prepare('INSERT INTO competition_members (id,room_id,role,name,normalized_name,session_hash,join_order,joined_at,last_seen_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(hostId,roomId,'host','Chủ phòng','__host__',hash,0,t,t)]);break;}catch(e){if(attempt===19)throw e;}}
 const me=await db().prepare('SELECT * FROM competition_members WHERE id=?').bind(hostId).first<MemberRow>();return json({room:await snapshot(roomId,me!)},201,{'Set-Cookie':cookieHeader(raw)});
}
export async function joinRoom(request:Request){
 await init();const body=await request.json() as {code?:string;name?:string};const code=String(body.code??'').trim();const name=String(body.name??'').trim().replace(/\s+/g,' ');if(!/^\d{4}$/.test(code))throw new ApiError(400,'Mã phòng phải gồm 4 chữ số.');if(name.length<2||name.length>24)throw new ApiError(400,'Tên phải dài từ 2 đến 24 ký tự.');
 const room=await db().prepare('SELECT * FROM competition_rooms WHERE code=?').bind(code).first<RoomRow>();if(!room||room.status!=='lobby'||room.expires_at<=now())throw new ApiError(404,'Phòng không tồn tại hoặc đã bắt đầu.');const count=await db().prepare("SELECT COUNT(*) count FROM competition_members WHERE room_id=? AND role='player'").bind(room.id).first<{count:number}>();if((count?.count??0)>=room.max_players)throw new ApiError(409,'Phòng đã đủ người.');
 const raw=token(),hash=await sha(raw),id=crypto.randomUUID(),t=now();try{const result=await db().prepare("INSERT INTO competition_members (id,room_id,role,name,normalized_name,session_hash,join_order,joined_at,last_seen_at) SELECT ?,?,?,?,?,?,COALESCE(MAX(join_order),0)+1,?,? FROM competition_members WHERE room_id=? HAVING SUM(CASE WHEN role='player' THEN 1 ELSE 0 END) < ?").bind(id,room.id,'player',name,normalize(name),hash,t,t,room.id,room.max_players).run();if(!result.meta.changes)throw new Error('full');}catch{throw new ApiError(409,'Tên đã được dùng trong phòng hoặc phòng vừa đủ người.');}const me=await db().prepare('SELECT * FROM competition_members WHERE id=?').bind(id).first<MemberRow>();return json({room:await snapshot(room.id,me!)},201,{'Set-Cookie':cookieHeader(raw)});
}
export async function getRoom(request:Request,roomId:string){const me=await auth(request,roomId);await db().prepare('UPDATE competition_members SET last_seen_at=? WHERE id=?').bind(now(),me.id).run();return json({room:await snapshot(roomId,{...me,last_seen_at:now()})});}
export async function readyRoom(request:Request,roomId:string){const me=await auth(request,roomId);if(me.role!=='player')throw new ApiError(403,'Chỉ người chơi có trạng thái sẵn sàng.');const room=await db().prepare('SELECT * FROM competition_rooms WHERE id=?').bind(roomId).first<RoomRow>();if(room?.status!=='lobby')throw new ApiError(409,'Phòng đã bắt đầu.');const body=await request.json() as {conclusion?:string;confidence?:string;ready?:boolean};const valid=getConfig(room.difficulty).initialOptions.some(o=>o.id===body.conclusion)&&['Thấp','Vừa','Cao'].includes(body.confidence??'');if(body.ready&&!valid)throw new ApiError(400,'Hãy hoàn tất nhận định ban đầu.');await db().prepare('UPDATE competition_members SET initial_conclusion=?,initial_confidence=?,ready=?,last_seen_at=? WHERE id=?').bind(body.conclusion??null,body.confidence??null,body.ready?1:0,now(),me.id).run();return getRoom(request,roomId);}
export async function startRoom(request:Request,roomId:string){const host=await auth(request,roomId);if(host.role!=='host')throw new ApiError(403,'Chỉ chủ phòng được bắt đầu.');const room=await db().prepare('SELECT * FROM competition_rooms WHERE id=?').bind(roomId).first<RoomRow>();if(room?.status!=='lobby')throw new ApiError(409,'Phòng không còn ở trạng thái chờ.');const players=(await db().prepare("SELECT * FROM competition_members WHERE room_id=? AND role='player' ORDER BY join_order").bind(roomId).all<MemberRow>()).results;if(players.length<2)throw new ApiError(409,'Cần ít nhất 2 người chơi.');if(players.some(p=>!p.ready||now()-p.last_seen_at>=15000))throw new ApiError(409,'Tất cả người chơi phải đang kết nối và sẵn sàng.');const t=now(),starts=t+5000,play=starts+CINEMATIC_SECONDS*1000,end=play+room.duration_seconds*1000;const statements=[db().prepare("UPDATE competition_rooms SET status='countdown',starts_at=?,play_starts_at=?,ends_at=?,revision=revision+1 WHERE id=? AND status='lobby'").bind(starts,play,end,roomId),...players.map(p=>{let state=createState('individual',room.difficulty);state={...state,chapterLimit:room.chapter_count as GameState['chapterLimit'],initial:{conclusion:p.initial_conclusion!,confidence:p.initial_confidence!},screen:'investigation',revision:1,updatedAt:new Date(t).toISOString()};return db().prepare('UPDATE competition_members SET game_state=?,version=1,score=0,score_updated_at=? WHERE id=?').bind(JSON.stringify(state),play,p.id);})];await db().batch(statements);return getRoom(request,roomId);}
export async function competitionAction(request:Request,roomId:string){const me=await auth(request,roomId);if(me.role!=='player'||!me.game_state)throw new ApiError(403,'Người chơi chưa bắt đầu.');await progressRoom(roomId);const room=await db().prepare('SELECT * FROM competition_rooms WHERE id=?').bind(roomId).first<RoomRow>();const t=now();if(!room||!['countdown','playing'].includes(room.status)||!room.play_starts_at||t<room.play_starts_at||!room.ends_at||t>=room.ends_at||me.completed_at)throw new ApiError(409,'Lượt thi đấu chưa mở hoặc đã kết thúc.');const body=await request.json() as {actionId?:string;expectedVersion?:number;action?:Action};if(!body.actionId||body.expectedVersion!==me.version||!body.action)throw new ApiError(409,'Tiến trình đã thay đổi; hãy tải lại trạng thái mới nhất.');const before=JSON.parse(me.game_state) as GameState;const after=applyCompetitionAction(before,body.action,new Date(t).toISOString());if(after===before)throw new ApiError(400,'Hành động không hợp lệ trong trạng thái hiện tại.');const events=scoreAction(before,body.action,after,body.actionId);const actionId=body.actionId;const d=db();const statements:D1PreparedStatement[]=[d.prepare('INSERT OR IGNORE INTO competition_actions (id,member_id,expected_version,processed,created_at) VALUES (?,?,?,?,?)').bind(actionId,me.id,me.version,0,t)];for(const event of events)statements.push(d.prepare('INSERT OR IGNORE INTO competition_score_events (id,room_id,member_id,action_id,event_key,kind,reference,delta,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM competition_members WHERE id=? AND version=?)').bind(crypto.randomUUID(),roomId,me.id,actionId,event.key,event.kind,event.reference,event.delta,t,me.id,me.version));const completed=after.screen==='result';statements.push(d.prepare('UPDATE competition_members SET game_state=?,version=version+1,score=score+COALESCE((SELECT SUM(delta) FROM competition_score_events WHERE action_id=?),0),score_updated_at=CASE WHEN COALESCE((SELECT SUM(delta) FROM competition_score_events WHERE action_id=?),0)<>0 THEN ? ELSE score_updated_at END,completed_at=CASE WHEN ? THEN ? ELSE completed_at END,ending=CASE WHEN ? THEN ? ELSE ending END,last_seen_at=? WHERE id=? AND version=? AND EXISTS (SELECT 1 FROM competition_actions WHERE id=? AND processed=0)').bind(JSON.stringify(after),actionId,actionId,t,completed?1:0,t,completed?1:0,after.result?.ending??null,t,me.id,me.version,actionId));statements.push(d.prepare('UPDATE competition_actions SET processed=1 WHERE id=?').bind(actionId));await d.batch(statements);const updated=await d.prepare('SELECT * FROM competition_members WHERE id=?').bind(me.id).first<MemberRow>();if(!updated||updated.version===me.version)throw new ApiError(409,'Tiến trình đã thay đổi; hãy thử lại.');await progressRoom(roomId);return json({room:await snapshot(roomId,updated)});
}
export async function heartbeat(request:Request,roomId:string){const me=await auth(request,roomId);await db().prepare('UPDATE competition_members SET last_seen_at=? WHERE id=?').bind(now(),me.id).run();return json({ok:true,serverNow:now()});}
export async function endRoom(request:Request,roomId:string){const me=await auth(request,roomId);if(me.role!=='host')throw new ApiError(403,'Chỉ chủ phòng được kết thúc.');const room=await db().prepare('SELECT status FROM competition_rooms WHERE id=?').bind(roomId).first<{status:string}>();if(!room)throw new ApiError(404,'Không tìm thấy phòng.');const status=room.status==='lobby'?'cancelled':'finished',reason=room.status==='lobby'?'host_cancelled':'host_ended';await db().prepare('UPDATE competition_rooms SET status=?,ends_at=?,end_reason=?,revision=revision+1 WHERE id=? AND status NOT IN (\'finished\',\'cancelled\')').bind(status,now(),reason,roomId).run();return getRoom(request,roomId);}
export async function removePlayer(request:Request,roomId:string){const host=await auth(request,roomId);if(host.role!=='host')throw new ApiError(403,'Chỉ chủ phòng được loại người chơi.');const body=await request.json() as {memberId?:string};await db().prepare("DELETE FROM competition_members WHERE id=? AND room_id=? AND role='player' AND EXISTS (SELECT 1 FROM competition_rooms WHERE id=? AND status='lobby')").bind(body.memberId??'',roomId,roomId).run();return getRoom(request,roomId);}
export async function leaveRoom(request:Request,roomId:string){const me=await auth(request,roomId);const room=await db().prepare('SELECT status FROM competition_rooms WHERE id=?').bind(roomId).first<{status:string}>();if(room?.status==='lobby'&&me.role==='player')await db().prepare('DELETE FROM competition_members WHERE id=?').bind(me.id).run();return json({ok:true},200,{'Set-Cookie':`${COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0`});}
export function handleApiError(error:unknown){if(error instanceof ApiError)return json({error:error.message},error.status);console.error(error);return json({error:'Không thể xử lý yêu cầu thi đấu.'},500);}
