import {describe,it,expect} from 'vitest';
import {answerComplete,caseCredibility,chapterReadiness,createState,deriveEnding,emptyAnswer,evaluateChallenge,missionEvidence,reduceGame,resultFor,simulateLinks,simulateNetwork,simulateRecovery,validateSave} from '../../game/engine';
import {tasks} from '../../game/tasks';
import {concepts} from '../../game/concepts';
import {evidence} from '../../game/evidence';
import {completeState,perfect} from '../fixtures';
import type {Evaluation,GameState,Verdict} from '../../game/types';
const verdict:Verdict={conclusion:'V3',evidence:['E08','E05','E04','E07'],note:''};
describe('Nội dung hồ sơ',()=>{
 it('đủ dữ kiện, nhiệm vụ, nguồn và tham chiếu',()=>{expect(evidence).toHaveLength(17);expect(tasks).toHaveLength(11);expect(concepts).toHaveLength(11);expect(new Set(evidence.map(e=>e.id)).size).toBe(17);expect(new Set(tasks.map(t=>t.concept)).size).toBe(11);for(const t of tasks){expect(t.criteria).toHaveLength(4);expect(t.feedback).toHaveLength(4);expect(t.hints).toHaveLength(2);for(const id of t.evidence)expect(evidence.find(e=>e.id===id)!.chapter).toBeLessThanOrEqual(t.chapter);expect(concepts.some(c=>c.id===t.concept)).toBe(true);}for(const c of concepts){expect(c.pages[0]).toBeGreaterThanOrEqual(1);expect(c.pages[1]).toBeLessThanOrEqual(37);expect(c.slide).toContain('Tiết');}});
 it('giữ thứ tự thời gian của lỗi, mạng, hội thoại và thao tác ẩn',()=>{const order=(id:string)=>evidence.find(e=>e.id===id)!.order;expect(order('E05')).toBeLessThan(order('E06'));expect(order('E07')).toBeLessThan(order('E08'));expect(evidence.find(e=>e.id==='E08')!.body.join()).toContain('No project deletion');});
 it('luồng tóm tắt không quá 2400 từ trước lựa chọn và chú giải mở rộng',()=>{const words=[...evidence.map(e=>e.summary),...tasks.map(t=>t.prompt),...concepts.map(c=>c.explanation)].join(' ').split(/\s+/).length;expect(words).toBeLessThan(2400);});
});
describe('Đánh giá lập luận',()=>{
 for(const t of tasks){it(`${t.id} đáp án chuẩn đạt 4/4`,()=>{expect(answerComplete(t.id,perfect[t.id])).toBe(true);expect(evaluateChallenge(t.id,perfect[t.id]).score).toBe(4);expect(answerComplete(t.id,emptyAnswer(t.id))).toBe(false);});}
 it('một tiêu chí sai giảm một điểm, không chấm theo tốc độ',()=>{expect(evaluateChallenge('T01',{kind:'classify',categories:{s1:'fact',s2:'unproven',s3:'unproven',s4:'fact'},evidence:['E07','E08']}).score).toBe(3);});
 it('mạng không thay cho cơ chế dữ liệu trong chuỗi',()=>{const e=evaluateChallenge('T02',{kind:'chain',order:['requirement','network','reject','failure'],relation:'decision'});expect(e.met).toEqual([false,false,true,true]);});
 it('không chấp nhận thẻ trùng hoặc thiếu thẻ ảnh hưởng',()=>{expect(evaluateChallenge('T06',{kind:'report',order:['req','incompat','test','test','measure','retest'],reason:'structure'}).met).toEqual([false,true,false,true]);});
 it('không đánh đồng A nguyên trạng với A′',()=>{expect(evaluateChallenge('T09',{kind:'choices',values:{model:'free',fromA:'autonomy',fromB:'standards',return:'higher'}}).score).toBe(3);});
 it('tăng trang và đổi màu không đủ để đạt năng lực cốt lõi',()=>{expect(evaluateChallenge('T10',{kind:'choices',values:{v1:'progress',v2:'best',v3:'capability',limit:'limited'}}).score).toBe(2);});
});
describe('Mô phỏng',()=>{
 it('giữ lỗi local khi chỉ thay mạng; mạng vẫn ảnh hưởng chia sẻ',()=>{expect(simulateNetwork(true,false).localSuccess).toBe(false);expect(simulateNetwork(false,false).localSuccess).toBe(false);expect(simulateNetwork(false,true)).toMatchObject({localSuccess:true,shareAvailable:false});expect(simulateNetwork(true,true)).toMatchObject({localSuccess:true,shareAvailable:true});});
 it('duyệt đồ thị cho kết quả khác dù cùng bốn liên kết',()=>{expect(simulateLinks('CA')).toMatchObject({count:4,success:false});expect(simulateLinks('BC')).toMatchObject({count:4,success:true,path:'A → B → C → D'});expect(simulateLinks(null).count).toBe(3);});
 it('chuỗi 55 phút thành công',()=>{expect(simulateRecovery(['A1','A2','A3','A4'])).toMatchObject({success:true,totalTime:55});});
 it('quá giờ, đảo điều kiện, chỉ chờ mạng đều thất bại',()=>{expect(simulateRecovery(['A1','A2','A3','A4','A6'])).toMatchObject({success:false,totalTime:85});expect(simulateRecovery(['A2','A1','A3','A4']).message).toContain('A2 thiếu điều kiện trước: A1');expect(simulateRecovery(['A7']).success).toBe(false);expect(simulateRecovery(['A1','A1']).success).toBe(false);});
});
describe('Trạng thái, kết thúc và bản lưu',()=>{
 it('chỉ ghi nhận chứng cứ sau lần nhận nhiệm vụ đầu tiên, kế thừa chứng cứ trùng và không reset',()=>{let s=reduceGame(createState(),{type:'begin',conclusion:'unknown',confidence:'Thấp'});s=reduceGame(s,{type:'evidence',id:'E03'});expect(s.opened).toContain('E03');expect(missionEvidence(s,'T02')).toEqual([]);s=reduceGame(s,{type:'acceptMission',id:'T02'});expect(s.missionProgress?.T02).toEqual([]);s=reduceGame(s,{type:'evidence',id:'E03'});expect(s.missionProgress?.T02).toEqual(['E03']);expect(missionEvidence(s,'T03')).toEqual(['E03']);s=reduceGame(s,{type:'acceptMission',id:'T03'});expect(s.missionProgress?.T03).toEqual(['E03']);const accepted=s;expect(reduceGame(s,{type:'acceptMission',id:'T03'})).toBe(accepted);s=reduceGame(s,{type:'evidence',id:'E04'});expect(s.missionProgress?.T02).toEqual(['E03','E04']);expect(s.missionProgress?.T03).toEqual(['E03','E04']);expect(validateSave(s).error).toBeNull();});
 it('không bỏ qua chương hay giải mã',()=>{let s=createState();expect(reduceGame(s,{type:'next'})).toBe(s);s=reduceGame(s,{type:'begin',conclusion:'unknown',confidence:'Thấp'});expect(reduceGame(s,{type:'chapter',chapter:3})).toBe(s);expect(reduceGame(s,{type:'submit',id:'T11',answer:perfect.T11,at:'x'})).toBe(s);expect(reduceGame(s,{type:'debrief'})).toBe(s);});
 it('khóa mềm yêu cầu lập luận cốt lõi trước khi giải mã chương',()=>{let s=reduceGame(createState(),{type:'begin',conclusion:'unknown',confidence:'Thấp'});const weak={kind:'classify' as const,categories:{s1:'fact',s2:'fact',s3:'fact',s4:'supported'},evidence:['E07','E08']};s=reduceGame(s,{type:'submit',id:'T01',answer:weak,at:'x'});s=reduceGame(s,{type:'submit',id:'T02',answer:perfect.T02,at:'x'});s=reduceGame(s,{type:'submit',id:'T03',answer:perfect.T03,at:'x'});expect(chapterReadiness(s,1)).toMatchObject({complete:true,ready:false});expect(chapterReadiness(s,1).unresolved[0]).toMatchObject({taskId:'T01',minimum:3});expect(reduceGame(s,{type:'debrief'})).toBe(s);s=reduceGame(s,{type:'submit',id:'T01',answer:perfect.T01,at:'y'});expect(chapterReadiness(s,1).ready).toBe(true);expect(reduceGame(s,{type:'debrief'}).screen).toBe('debrief');});
  it('độ tin cậy phản ánh lập luận hiện tại và trừ điểm khi sửa đáp án hoặc mở gợi ý',()=>{
    let s=reduceGame(createState(),{type:'begin',conclusion:'unknown',confidence:'Thấp'});
    const before=caseCredibility(s).score;
    s=reduceGame(s,{type:'submit',id:'T01',answer:perfect.T01,at:'x'});
    expect(caseCredibility(s).score).toBeGreaterThan(before);
    const scoreFirstSubmit=caseCredibility(s).score;
    // Sửa và nộp lại cùng 1 nhiệm vụ bị trừ 2 điểm nộp lại
    s=reduceGame(s,{type:'submit',id:'T01',answer:{kind:'classify',categories:{s1:'fact',s2:'fact',s3:'unproven',s4:'unproven'},evidence:['E07','E08']},at:'y'});
    expect(caseCredibility(s).score).toBeLessThan(scoreFirstSubmit);
    // Mở khóa gợi ý chứng cứ bị trừ 2 điểm
    const beforeUnlock=caseCredibility(s).score;
    s=reduceGame(s,{type:'unlockEvidenceHint',id:'E01'});
    expect(s.unlockedEvidenceHints).toContain('E01');
    expect(caseCredibility(s).score).toBe(beforeUnlock - 2);
  });
 it('chơi đủ 11 nhiệm vụ và các giải mã mới đến kết luận',()=>{const s=completeState();expect(s.screen).toBe('verdict');expect(s.debriefs).toEqual([1,2,3]);expect(Object.keys(s.answers)).toHaveLength(11);expect(validateSave(s).state).not.toBeNull();});
 it('thi đấu một chương chuyển thẳng sang kết luận và chỉ chấm nội dung đã chơi',()=>{let s:GameState={...reduceGame(createState(),{type:'begin',conclusion:'unknown',confidence:'Thấp'}),chapterLimit:1};for(const id of ['T01','T02','T03'])s=reduceGame(s,{type:'submit',id,answer:perfect[id],at:'x'});s=reduceGame(reduceGame(s,{type:'debrief'}),{type:'next'});expect(s).toMatchObject({screen:'verdict',chapter:1,unlocked:1,debriefs:[1]});expect(validateSave(s).error).toBeNull();const finished=reduceGame(s,{type:'finish',verdict:{conclusion:'V3',evidence:['E04'],note:''}});expect(finished).toMatchObject({screen:'result',result:{score:12,ending:4}});expect(Object.keys(finished.result!.evaluations)).toEqual(['T01','T02','T03']);expect(validateSave(finished).error).toBeNull();});
 it('bốn kết thúc có điều kiện và thứ tự đúng',()=>{const s=completeState();expect(resultFor(s,verdict)).toMatchObject({ending:4,score:44});expect(resultFor(s,{...verdict,conclusion:'V1'}).ending).toBe(1);expect(resultFor(s,{...verdict,conclusion:'V2'}).ending).toBe(1);expect(resultFor(s,{...verdict,conclusion:'V4'}).ending).toBe(2);expect(resultFor(s,{...verdict,evidence:['E01']}).ending).toBe(2);s.answers.T11={kind:'recovery',order:['A1','A2','A3','A4','A6'],reality:'available',conclusion:'limited'};expect(resultFor(s,verdict).ending).toBe(3);});
 it('ngưỡng 29 và 30 bằng điểm từng nhiệm vụ hợp lệ',()=>{const scores=[3,3,2,2,3,2,2,2,3,3,4];const evals=Object.fromEntries(tasks.map((t,i)=>[t.id,{score:scores[i],met:[],}])) as Record<string,Evaluation>;expect(scores.reduce((a,b)=>a+b)).toBe(29);expect(deriveEnding(evals,verdict,simulateRecovery(['A1','A2','A3','A4'])).ending).toBe(2);evals.T03.score=3;expect(deriveEnding(evals,verdict,simulateRecovery(['A1','A2','A3','A4'])).ending).toBe(4);});
 it('ghi nhận không lặp khi bấm nhanh, lưu cả đáp án đầu và gần nhất',()=>{let s=reduceGame(createState(),{type:'begin',conclusion:'unknown',confidence:'Vừa'});const action={type:'submit' as const,id:'T01',answer:perfect.T01,at:'x'};s=reduceGame(s,action);s=reduceGame(s,action);expect(s.attempts.T01).toHaveLength(1);s=reduceGame(s,{...action,answer:{kind:'classify',categories:{s1:'fact',s2:'fact',s3:'unproven',s4:'supported'},evidence:['E07','E08']}});expect(s.attempts.T01).toHaveLength(2);expect(evaluateChallenge('T01',s.answers.T01).score).toBe(3);});
 it('tính lại điểm giả từ bản lưu và không tăng attempts khi reload',()=>{let s=completeState();s=reduceGame(s,{type:'finish',verdict});s.result!.score=999;s.result!.ending=1;s.attempts.T01[0].evaluation.score=999;const loaded=validateSave(JSON.parse(JSON.stringify(s))).state!;expect(loaded.result!.score).toBe(44);expect(loaded.result!.ending).toBe(4);expect(loaded.attempts.T01[0].evaluation.score).toBe(4);expect(loaded.attempts.T01).toHaveLength(1);});
 it('từ chối sai cấu trúc, sai phiên bản, đáp án lạ và timeline khóa',()=>{expect(validateSave({}).state).toBeNull();expect(validateSave({...createState(),caseVersion:'old'}).state).toBeNull();expect(validateSave({...completeState(),opened:['E99']}).state).toBeNull();expect(validateSave({...createState(),unlocked:3}).state).toBeNull();const s=completeState();s.answers.T07={kind:'choices',values:{solution:'injected'}};expect(validateSave(s).state).toBeNull();});
 it('kết quả cố định cho đến khi mở bản điều tra mới',()=>{const s=reduceGame(completeState(),{type:'finish',verdict});expect(reduceGame(s,{type:'draft',id:'T01',answer:perfect.T01})).toBe(s);expect(reduceGame(s,{type:'reopen'}).screen).toBe('investigation');});
});
